//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface NADAppSerializer : NSObject
{
    NSString *_fileName;
    Class _entityClass;
}

+ (id)applicationSerializer;
@property(readonly, nonatomic) Class entityClass; // @synthesize entityClass=_entityClass;
@property(readonly, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
- (void).cxx_destruct;
- (_Bool)setVersion:(unsigned long long)arg1 forApplicationAtURL:(id)arg2;
- (unsigned long long)versionForApplicationAtURL:(id)arg1;
- (id)objectAtDirectory:(id)arg1;
- (_Bool)persistObject:(id)arg1 toDirectory:(id)arg2 error:(id *)arg3;
- (id)URLForFileInDirectory:(id)arg1;
- (id)initWithDefaultFileName:(id)arg1 entityClass:(Class)arg2;

@end

