/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 5:03:48 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libPPMDataModel.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	float list;
	unsigned long long count;
	unsigned long long size;
} SCD_Struct_OT1;

typedef struct {
	unsigned traceResistance25C : 1;
	unsigned traceResistanceTemperatureCoeff : 1;
} SCD_Struct_OT2;

