//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIViewController, WDProfile;
@protocol WDIntroFlowComponentDelegate;

@interface WDIntroFlowComponent : NSObject
{
    WDProfile *_profile;
    UIViewController *_rootViewController;
    id <WDIntroFlowComponentDelegate> _delegate;
}

+ (_Bool)introFlowEnabledWithHealthStore:(id)arg1;
@property(nonatomic) __weak id <WDIntroFlowComponentDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) WDProfile *profile; // @synthesize profile=_profile;
- (void).cxx_destruct;
- (void)presentIfNecessary;
- (id)initWithProfile:(id)arg1 rootViewController:(id)arg2;

@end

