//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WDHealthTableViewController.h"

#import "WDUserActivityResponder-Protocol.h"

@class NSString;

@interface WDSourcesViewController : WDHealthTableViewController <WDUserActivityResponder>
{
    int _sourceListUpdateToken;
}

+ (id)tableViewSectionClasses;
- (id)applyTransitionActivity:(id)arg1;
- (void)applyChangeActivity:(id)arg1;
- (void)_updateActivityForViewDidAppear;
- (id)uniqueUserActivityType;
- (void)pushViewController:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (void)reloadSectionData;
- (void)_registerForSourceChangeNotifications;
- (void)viewDidLoad;
- (id)initWithProfile:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

