//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface VSSpeechCache : NSObject
{
    NSString *_dirPath;
    NSString *_preinstalledCacheDir;
}

+ (id)defaultCacheStore;
@property(retain, nonatomic) NSString *preinstalledCacheDir; // @synthesize preinstalledCacheDir=_preinstalledCacheDir;
@property(retain, nonatomic) NSString *dirPath; // @synthesize dirPath=_dirPath;
- (void).cxx_destruct;
- (void)deleteCache;
- (unsigned long long)totalCacheSize;
- (void)cleanCache;
- (_Bool)isPreinstalledCacheAvailableForRequest:(id)arg1;
- (id)cacheDataForKey:(id)arg1;
- (id)preinstalledCacheForText:(id)arg1 language:(id)arg2 gender:(long long)arg3;
- (id)addCache:(id)arg1;
- (id)initWithStorePath:(id)arg1;

@end

