//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuickSpeak/__CKFullScreenBalloonViewControllerPhone_QSExtras_super.h>

@interface CKFullScreenBalloonViewControllerPhone_QSExtras : __CKFullScreenBalloonViewControllerPhone_QSExtras_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)setBalloonView:(id)arg1;

@end

