//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AccessibilitySettingsLoader/__ZoomUI_SBFluidSwitcherGestureManager_super.h>

@interface ZoomUI_SBFluidSwitcherGestureManager : __ZoomUI_SBFluidSwitcherGestureManager_super
{
}

+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;

@end

