//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDate;
@protocol FRFeldsparContext;

@protocol FRAppCacheSnapshotter
@property(readonly, nonatomic) _Bool snapshotPreparedAndWaitingForRestoration;
@property(readonly, nonatomic) NSDate *existingSnapshotCreationDate;
- (void)finalizeRestoreOfCachesDirectory;
- (void)prepareToRestoreSnapshotAndKillApp;
- (void)removeExistingSnapshotWithCompletionHandler:(void (^)(_Bool, NSError *))arg1;
- (void)snapshotWithCompletionHandler:(void (^)(_Bool, NSError *))arg1;
- (id)initWithFeldsparContext:(id <FRFeldsparContext>)arg1;
@end

