//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIActivityViewController.h>

@interface FRArticleMarkingSharrowActivity : UIActivityViewController
{
}

- (id)initWithHeadlineContext:(id)arg1 location:(long long)arg2 withArticleMarkingState:(id)arg3 feldsparContext:(id)arg4 parentViewController:(id)arg5 targetIsVideo:(_Bool)arg6 referral:(id)arg7 completion:(CDUnknownBlockType)arg8;

@end

