//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIColor;

@protocol FRBarStyle <NSObject>
@property(readonly, nonatomic) _Bool hideTitleOnTop;
@property(readonly, nonatomic) _Bool transparentNavigationBarPreferred;
@property(readonly, nonatomic) _Bool useDarkBackgroundThemeForTitleImage;
@property(readonly, nonatomic) UIColor *toolbarTintColor;
@property(readonly, nonatomic) UIColor *toolbarBackgroundColor;
@property(readonly, nonatomic) long long statusBarStyle;
@property(readonly, nonatomic) UIColor *navigationBarTintColor;
@property(readonly, nonatomic) UIColor *navigationBarBackgroundColor;
@end

