//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FRFeedCollectionViewCell, NSArray, UIWindow;

@protocol FRFeedCollectionViewCellDelegate <NSObject>

@optional
- (_Bool)shouldAttemptToRenderImageSynchronouslyForCell:(FRFeedCollectionViewCell *)arg1;
- (_Bool)shouldAnimateImageLoadForCell:(FRFeedCollectionViewCell *)arg1;
- (NSArray *)accessibilityCustomActionsForFeedCollectionViewCell:(FRFeedCollectionViewCell *)arg1;
- (void)feedCollectionViewCell:(FRFeedCollectionViewCell *)arg1 shouldDisplayShareSheet:(_Bool)arg2;
- (void)feedCollectionViewCell:(FRFeedCollectionViewCell *)arg1 movedToWindow:(UIWindow *)arg2;
@end

