//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FRFeedLayoutBlueprintBookmark-Protocol.h"

@class NSString;

@interface FRFeedCollectionViewScrollBookmark : NSObject <FRFeedLayoutBlueprintBookmark>
{
    _Bool _aggregate;
    NSString *_headlineTileInfoID;
    double _scrollOffsetFromCenter;
    unsigned long long _offsetType;
    struct CGSize _viewportSize;
}

+ (_Bool)supportsSecureCoding;
+ (id)topOfFeed;
@property(nonatomic, getter=isAggregate) _Bool aggregate; // @synthesize aggregate=_aggregate;
@property(nonatomic) struct CGSize viewportSize; // @synthesize viewportSize=_viewportSize;
@property(nonatomic) unsigned long long offsetType; // @synthesize offsetType=_offsetType;
@property(nonatomic) double scrollOffsetFromCenter; // @synthesize scrollOffsetFromCenter=_scrollOffsetFromCenter;
@property(copy, nonatomic) NSString *headlineTileInfoID; // @synthesize headlineTileInfoID=_headlineTileInfoID;
- (void).cxx_destruct;
- (id)debugDescription;
@property(readonly, nonatomic) _Bool hasPrefetchedViewport;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

