//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FRFeedCollectionViewLayoutSectionDescriptorForYou.h"

@interface FRFeedCollectionViewLayoutSectionDescriptorMoreVideos : FRFeedCollectionViewLayoutSectionDescriptorForYou
{
}

- (id)layoutAttributesForBackground;
- (_Bool)needsTileInfoAggregation;
- (long long)sectionFooterStyle;
- (id)sectionThemeColor;
- (id)initWithFeedSettings:(id)arg1 group:(id)arg2 feedLayoutSearchConfiguration:(id)arg3 headerStyle:(long long)arg4 buttonController:(id)arg5 feldsparContext:(id)arg6 groupSizeCalculator:(id)arg7;

@end

