//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSString;

@protocol FRFeedLayoutBlueprintBookmark <NSSecureCoding, NSCopying>
@property(readonly, nonatomic) _Bool hasPrefetchedViewport;
@property(readonly, nonatomic, getter=isAggregate) _Bool aggregate;
@property(readonly, nonatomic) struct CGSize viewportSize;
@property(readonly, nonatomic) unsigned long long offsetType;
@property(readonly, nonatomic) double scrollOffsetFromCenter;
@property(readonly, copy, nonatomic) NSString *headlineTileInfoID;
@end

