//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FRPurchaseViewController;

@protocol FRPurchaseViewControllerDelegate <NSObject>
- (void)purchaseViewControllerWebAccessAuthenticationSubscribed:(FRPurchaseViewController *)arg1;
- (void)purchaseViewControllerAppStorePurchaseSuccessful:(FRPurchaseViewController *)arg1;
- (void)purchaseViewControllerDismissed:(FRPurchaseViewController *)arg1;
@end

