//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (FRAdditions)
- (double)heightConstrainedToWidth:(double)arg1 font:(id)arg2 singleLine:(_Bool)arg3;
- (_Bool)fr_hasPrefixEquivalentToString:(id)arg1;
- (_Bool)fr_isEquivalentToString:(id)arg1;
- (id)fr_StringByTrimmingLeadingWhiteSpace;
- (id)fr_accessibilityAttributedStringForHighPriorityAnnouncement;
- (id)fr_accessibilityAttributedStringWithLowPitchPrefix:(id)arg1;
- (id)fr_accessibilityLowPitchAttributedString;
- (id)fr_stringByDecodingHTMLEntities;
- (id)fr_stripHTMLTags;
- (id)fr_encodeHTMLEntities;
- (id)fr_convertNewlinesToPTags;
- (id)fr_stringInitials;
@end

