//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, UITraitCollection;
@protocol FCHeadlineProviding;

@protocol TSForYouGroupSizeCalculatorType
- (double)moreVideoGroupHeight:(NSString *)arg1 withSectionTitle:(NSString *)arg2 headline:(id <FCHeadlineProviding>)arg3 viewportSize:(struct CGSize)arg4 screenScale:(double)arg5 traitCollection:(UITraitCollection *)arg6 contentSizeCategory:(NSString *)arg7;
- (double)topVideoGroupHeight:(NSString *)arg1 withSectionTitle:(NSString *)arg2 headline:(id <FCHeadlineProviding>)arg3 viewportSize:(struct CGSize)arg4 screenScale:(double)arg5 traitCollection:(UITraitCollection *)arg6 contentSizeCategory:(NSString *)arg7;
@end

