//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol TSStatusBarTapHandlerType;

@protocol TSStatusBarTapManagerType
- (void)notifyHandlersWithTapWithCount:(long long)arg1;
- (void)deregisterWithHandler:(id <TSStatusBarTapHandlerType>)arg1;
- (void)registerWithHandler:(id <TSStatusBarTapHandlerType>)arg1;
@end

