//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface ACXTimedIdentifierList : NSObject
{
    CDUnknownBlockType _timeoutHandler;
    NSMutableDictionary *_list;
    NSObject<OS_dispatch_source> *_sweepTimer;
    NSObject<OS_dispatch_queue> *_queue;
    double _timeoutInSeconds;
}

@property(readonly) double timeoutInSeconds; // @synthesize timeoutInSeconds=_timeoutInSeconds;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain) NSObject<OS_dispatch_source> *sweepTimer; // @synthesize sweepTimer=_sweepTimer;
@property(readonly) NSMutableDictionary *list; // @synthesize list=_list;
@property(copy) CDUnknownBlockType timeoutHandler; // @synthesize timeoutHandler=_timeoutHandler;
- (void).cxx_destruct;
- (_Bool)containsIdentifier:(id)arg1;
- (_Bool)removeIdentifier:(id)arg1;
- (void)updateTimeOnIdentifier:(id)arg1;
- (_Bool)addIdentifierIfNotPresent:(id)arg1;
- (id)initWithTimeout:(double)arg1;

@end

