//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FPDExtension, NSDate, NSError, NSString, NSURL;
@protocol OS_dispatch_queue;

@interface FPDExtensionIndexer : NSObject
{
    NSString *_domain;
    NSObject<OS_dispatch_queue> *_queue;
    NSURL *_stateURL;
    _Bool _needsIndexing;
    _Bool _isIndexing;
    _Bool _enabled;
    _Bool _invalidated;
    unsigned long long _batchIndexedCount;
    unsigned long long _batchIndexedCountSinceLastIndexing;
    unsigned long long _consecutiveBatchErrorCount;
    unsigned long long _consecutiveCrashCount;
    NSDate *_lastIndexingStartDate;
    NSError *_lastError;
    FPDExtension *_extension;
}

@property(nonatomic) __weak FPDExtension *extension; // @synthesize extension=_extension;
- (void).cxx_destruct;
- (void)dumpStateTo:(id)arg1;
- (void)setIndexingEnabled:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)signalChangesWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_signalChangesWithCompletionHandler:(CDUnknownBlockType)arg1;
- (_Bool)dropIndexWithError:(id *)arg1;
- (void)signalNeedsReindexFromScratchWithCompletionHandler:(CDUnknownBlockType)arg1;
- (_Bool)canContinueIndexing;
- (void)_indexOneBatchIfPossible;
- (void)_handleOneBatchCompletionWithError:(id)arg1 hasMoreChanges:(_Bool)arg2;
- (_Bool)readNeedsIndexingFromDisk;
- (void)clearNeedsIndexingOnDisk;
- (void)persistNeedsIndexingOnDisk;
- (void)invalidate;
- (void)start;
- (id)description;
- (id)initWithExtension:(id)arg1 domain:(id)arg2 enabled:(_Bool)arg3;

@end

