/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:21:01 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/OS_nw_link_info.h>

@class NSString;

@interface NWConcrete_nw_link_info : NSObject <OS_nw_link_info> {

	int flow_control_status;
	unsigned char link_quality;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
@end

