/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:21:01 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/OS_nw_read_request.h>

@protocol OS_dispatch_data, OS_nw_content_context, OS_nw_error, OS_nw_array;
@class NSObject, NSString;

@interface NWConcrete_nw_read_request : NSObject <OS_nw_read_request> {

	NWConcrete_nw_read_request* next;
	/*^block*/id data_completion;
	/*^block*/id data_multiple_completion;
	/*^block*/id buffer_completion;
	int variant;
	unsigned long long min;
	unsigned long long max;
	unsigned long long progress;
	char* buffer;
	NSObject*<OS_dispatch_data> data;
	NSObject*<OS_nw_content_context> context;
	NSObject*<OS_nw_error> error;
	NSObject*<OS_nw_array> read_array;
	unsigned reported : 1;
	unsigned is_complete : 1;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
-(NSString *)description;
@end

