//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreServices/SSVMediaSocialPostAttachment.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface MediaSocialPostAttachment : SSVMediaSocialPostAttachment <NSCopying>
{
    NSString *_assetToken;
    NSString *_assetTokenType;
    double _uploadTime;
}

@property(nonatomic) double uploadTime; // @synthesize uploadTime=_uploadTime;
@property(copy, nonatomic) NSString *assetTokenType; // @synthesize assetTokenType=_assetTokenType;
@property(copy, nonatomic) NSString *assetToken; // @synthesize assetToken=_assetToken;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

