//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface UpdatableAssetControllerDeferredScheduleValues : NSObject
{
    _Bool _scheduledInBackground;
    NSURL *_manifestURL;
    NSURL *_bundledManifestURL;
    NSString *_clientIdentifier;
    NSString *_userAgent;
    CDUnknownBlockType _completion;
}

@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) _Bool scheduledInBackground; // @synthesize scheduledInBackground=_scheduledInBackground;
@property(retain, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(retain, nonatomic) NSString *clientIdentifier; // @synthesize clientIdentifier=_clientIdentifier;
@property(retain, nonatomic) NSURL *bundledManifestURL; // @synthesize bundledManifestURL=_bundledManifestURL;
@property(retain, nonatomic) NSURL *manifestURL; // @synthesize manifestURL=_manifestURL;
- (void).cxx_destruct;

@end

