//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIFont.h>

@interface UIFont (ConvenienceFonts)
+ (id)preferredFontForTextStyle:(id)arg1 minimumContentSizeCategory:(id)arg2 maximumContentSizeCategory:(id)arg3;
+ (id)preferredFontForTextStyle:(id)arg1 symbolicTraits:(unsigned int)arg2 options:(unsigned long long)arg3;
+ (id)preferredFontForTextStyle:(id)arg1 symbolicTraits:(unsigned int)arg2;
+ (id)constrainedCaption2Font;
+ (id)constrainedBodyFont;
@end

