//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class NSAttributedString, NSString;

@interface _TtC5Files8DOCLabel : UILabel
{
    // Error parsing type: , name: useAttributedText
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSAttributedString *attributedText;
@property(nonatomic, copy) NSString *text;

@end

