//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DocumentManager/DOCDocumentSource.h>

@class NSString, UIImage;

@interface _TtC5Files21DOCFileProviderSource : DOCDocumentSource
{
    // Error parsing type: , name: fileProvider
    // Error parsing type: , name: dropAction
    // Error parsing type: , name: actions
    // Error parsing type: , name: uiActions.storage
    // Error parsing type: , name: containingApplicationIdentifier.storage
    // Error parsing type: , name: _displayName.storage
    // Error parsing type: , name: _icon.storage
    // Error parsing type: , name: fileProviderIdentifier
    // Error parsing type: , name: enumerationIdentifier
    // Error parsing type: , name: isProviderEnabled
    // Error parsing type: , name: requiresCustomEnumerationProperties
    // Error parsing type: , name: defaultSorting
    // Error parsing type: , name: sortingModes
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic, readonly) _Bool isAvailableSystemWide;
@property(nonatomic, retain) UIImage *icon;
@property(nonatomic, copy) NSString *displayName;

@end

