//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DOCServiceTransitionProtocol-Protocol.h"

@interface _TtC5Files30DOCServiceTransitionController : NSObject <DOCServiceTransitionProtocol>
{
    // Error parsing type: , name: itemCollection
    // Error parsing type: , name: item
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)endTransition;
- (void)startTransition;
- (void)getDisplayInformation:(_Bool)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)setHasProgress:(_Bool)arg1 loadingFractionCompleted:(double)arg2 setIsIndeterminate:(_Bool)arg3;

@end

