//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "LSOpenResourceOperationDelegate-Protocol.h"

@interface _TtCV5Files11LaunchUtilsP33_8C6F748C1B152D57B0BF02E0128C25FD15OpenAppDelegate : NSObject <LSOpenResourceOperationDelegate>
{
    // Error parsing type: , name: completionBlock
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)openResourceOperation:(id)arg1 didFailWithError:(id)arg2;
- (void)openResourceOperationDidComplete:(id)arg1;
- (void)openResourceOperation:(id)arg1 didFinishCopyingResource:(id)arg2;

@end

