//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DOCServicePopoverTrackerProtocol-Protocol.h"

@interface _TtC5Files34DOCServicePopoverTrackerController : NSObject <DOCServicePopoverTrackerProtocol>
{
    // Error parsing type: , name: itemCollection
    // Error parsing type: , name: item
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)getFrameForRegion:(unsigned long long)arg1 waitForNewThumbnail:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)getFrameForRegion:(unsigned long long)arg1 completionBlock:(CDUnknownBlockType)arg2;

@end

