//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIColor, UIFont;

@protocol DOC_ICQBannerViewProtocol
@property(nonatomic, retain) UIFont *font;
@property(nonatomic, retain) UIColor *textColor;
@property(nonatomic, copy) UIFont *linkTextFont;
@property(nonatomic, copy) UIColor *linkTextColor;
@end

