//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface SSSOccludingCoveringView : UIView
{
    UIView *_backgroundColorView;
    long long _style;
    UIColor *_backgroundColorForBackgroundStyle;
}

@property(copy, nonatomic) UIColor *backgroundColorForBackgroundStyle; // @synthesize backgroundColorForBackgroundStyle=_backgroundColorForBackgroundStyle;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

