//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MLDActiveTransaction, MLDMediaLibraryWriter, NSError;

@protocol MLDMediaLibraryWriterDelegate <NSObject>

@optional
- (void)mediaLibraryWriter:(MLDMediaLibraryWriter *)arg1 didDestroyTransaction:(MLDActiveTransaction *)arg2;
- (void)mediaLibraryWriter:(MLDMediaLibraryWriter *)arg1 terminatedTransaction:(MLDActiveTransaction *)arg2 withError:(NSError *)arg3;
@end

