//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MLDDAAPImportOperation.h"

@interface MLDPurchaseHistoryImportOperation : MLDDAAPImportOperation
{
}

- (void)updateImportProgress:(float)arg1;
- (shared_ptr_7b646331)importItemFromDAAPElement:(shared_ptr_be2f9a71)arg1;
- (_Bool)_performPurchaseHistoryImportWithTransaction:(id)arg1;
- (void)main;
- (unsigned long long)importSource;

@end

