//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AXActionSheetUIServer/AXUIAlertDelegate-Protocol.h>
#import <AXActionSheetUIServer/AXUIContentViewControllerDelegate-Protocol.h>
#import <AXActionSheetUIServer/AXUIService-Protocol.h>

@class NSString, UIAlertController, UIViewController;

@interface AXActionSheetUIServer : NSObject <AXUIAlertDelegate, AXUIService, AXUIContentViewControllerDelegate>
{
    UIAlertController *_alertController;
    UIViewController *_emptyViewController;
    NSString *_alertIdentifier;
}

@property(retain, nonatomic) NSString *alertIdentifier; // @synthesize alertIdentifier=_alertIdentifier;
- (void).cxx_destruct;
- (void)alertWithIdentifierWasActivated:(id)arg1;
- (void)alertWithIdentifierDidDisappear:(id)arg1;
- (double)desiredWindowLevelForContentViewController:(id)arg1 userInteractionEnabled:(_Bool)arg2;
- (id)processMessage:(id)arg1 withIdentifier:(unsigned long long)arg2 fromClientWithIdentifier:(id)arg3 error:(id *)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

