//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SSSPathView, _SSSAnimatableBorderCornerRadiusView;

@interface SSSWaitingForImageIdentifierUpdatesAlertContentView : UIView
{
    _SSSAnimatableBorderCornerRadiusView *_outerRingView;
    SSSPathView *_innerPieView;
    double _progress;
}

@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
- (id)_shapeLayerPathForProgress:(double)arg1;
- (void)layoutSubviews;

@end

