//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppleConnectClient/NSObject-Protocol.h>

@class UIViewController;
@protocol ACExecutionEnvironment;

@protocol ACExtenstionProxyConsumer <NSObject>
@property(readonly, nonatomic) long long presentationStyle;
@property(readonly, nonatomic) id <ACExecutionEnvironment> executionEnvironment;
- (void)dismissRemoteViewControllerWithCompletion:(void (^)(void))arg1;
- (_Bool)presentRemoteViewController:(UIViewController *)arg1 withCompletion:(void (^)(void))arg2;
@end

