//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "B238SetupBaseViewController.h"

@class NSString;

@interface B238SetupLiveOnViewController : B238SetupBaseViewController
{
    NSString *_iCloudUserID;
    NSString *_iTunesUserID;
}

@property(copy, nonatomic) NSString *iTunesUserID; // @synthesize iTunesUserID=_iTunesUserID;
@property(copy, nonatomic) NSString *iCloudUserID; // @synthesize iCloudUserID=_iCloudUserID;
- (void).cxx_destruct;
- (void)handleLiveOnButton:(id)arg1;
- (void)handleDismissButton:(id)arg1;
- (void)handleDevelopmentButton:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

