//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "B238SetupBaseViewController.h"

@class NSObject, NSString, UIActivityIndicatorView, UIImageView, UILabel, UIView;
@protocol OS_dispatch_source;

@interface B238SetupProgressViewController : B238SetupBaseViewController
{
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UIView *_progressView;
    UIActivityIndicatorView *_progressSpinner;
    UILabel *_progressLabel;
    NSString *_progressTextPending;
    UIImageView *_progressDoneImage;
    NSObject<OS_dispatch_source> *_progressTextTimer;
}

- (void).cxx_destruct;
- (void)_updateProgressText:(id)arg1 afterDelay:(double)arg2;
- (void)handleProgressEvent:(unsigned int)arg1;
- (void)handleDismissButton:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

