//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SVSBaseMainController.h"

@class NSString, NSUUID, SFDeviceSetupSessioniOS, SVSCommonNavController, UIStoryboard, UIViewController, VPScannerViewController, iOSSetupAuthViewController, iOSSetupBackupSyncViewController, iOSSetupDoneViewController, iOSSetupFinishViewController, iOSSetupStartViewController;

@interface iOSSetupMainController : SVSBaseMainController
{
    _Bool _dismissed;
    _Bool _homePressed;
    _Bool _loggedUsageStart;
    _Bool _loggedUsageDone;
    SFDeviceSetupSessioniOS *_setupSession;
    UIStoryboard *_storyboard;
    iOSSetupAuthViewController *_vcAuth;
    iOSSetupBackupSyncViewController *_vcBackupSync;
    iOSSetupDoneViewController *_vcDone;
    iOSSetupFinishViewController *_vcFinish;
    SVSCommonNavController *_vcNav;
    iOSSetupStartViewController *_vcStart;
    VPScannerViewController *_vcVisualAuth;
    UIViewController *_vcVisualAuthParent;
    unsigned long long _visualAuthNextTicks;
    _Bool _visualAuthTryingCode;
    unsigned long long _viewAppearedTicks;
    unsigned char _otherDeviceClassCode;
    unsigned char _otherDeviceModelCode;
    unsigned char _otherDeviceColorCode;
    unsigned int _badPINCount;
    int _testMode;
    NSUUID *_deviceIdentifier;
    NSString *_myAppleID;
    NSString *_otherDeviceClassName;
}

+ (_Bool)_isSecureForRemoteViewService;
@property(nonatomic) int testMode; // @synthesize testMode=_testMode;
@property(nonatomic) unsigned int badPINCount; // @synthesize badPINCount=_badPINCount;
@property(copy, nonatomic) NSString *otherDeviceClassName; // @synthesize otherDeviceClassName=_otherDeviceClassName;
@property(nonatomic) unsigned char otherDeviceColorCode; // @synthesize otherDeviceColorCode=_otherDeviceColorCode;
@property(nonatomic) unsigned char otherDeviceModelCode; // @synthesize otherDeviceModelCode=_otherDeviceModelCode;
@property(nonatomic) unsigned char otherDeviceClassCode; // @synthesize otherDeviceClassCode=_otherDeviceClassCode;
@property(copy, nonatomic) NSString *myAppleID; // @synthesize myAppleID=_myAppleID;
@property(copy, nonatomic) NSUUID *deviceIdentifier; // @synthesize deviceIdentifier=_deviceIdentifier;
- (void).cxx_destruct;
- (void)showFinishUI;
- (void)showDoneUI:(id)arg1;
- (void)showBackupSyncUI:(unsigned int)arg1 info:(id)arg2;
- (void)_tryPIN:(id)arg1;
- (void)_handleVisualAuthScannedCode:(id)arg1;
- (void)_handleVisualAuthEvent:(long long)arg1;
- (void)showAuthUIWithFlags:(unsigned int)arg1 throttleSeconds:(int)arg2 animated:(_Bool)arg3;
- (void)_sessionHandleProgress:(unsigned int)arg1 info:(id)arg2;
- (void)_sessionStart:(id)arg1;
- (void)logUsageDone:(int)arg1;
- (void)logUsageStart:(int)arg1;
- (void)_handleHomeButtonPressed;
- (void)handleButtonActions:(id)arg1;
- (void)dismiss:(int)arg1 animated:(_Bool)arg2;
- (void)dismiss:(int)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)configureWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

