//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSLayoutConstraint.h>

@interface NSLayoutConstraint (SVSLayoutConstraintExtensions)
@property(nonatomic) double iPhoneSEConstant;
@property(nonatomic) double d22Constant;
@end

