//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSLayoutConstraint, SVSCardContainerView;

@interface SVSBaseViewController : UIViewController
{
    NSLayoutConstraint *_bottomMarginConstraint;
    SVSCardContainerView *_containerView;
    id _mainController;
}

@property(retain, nonatomic) id mainController; // @synthesize mainController=_mainController;
@property(retain, nonatomic) SVSCardContainerView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) NSLayoutConstraint *bottomMarginConstraint; // @synthesize bottomMarginConstraint=_bottomMarginConstraint;
- (void).cxx_destruct;
- (void)viewDidAppear:(_Bool)arg1;
- (void)cancelProxCardDraggingWithCompletion:(CDUnknownBlockType)arg1;

@end

