//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpringBoardUIServices/SBUIRemoteAlertServiceViewController.h>

@class NSDictionary;

@interface SVSBaseMainController : SBUIRemoteAlertServiceViewController
{
    NSDictionary *_userInfo;
}

@property(copy, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;
- (void)dismiss:(int)arg1;
- (unsigned long long)desiredHomeButtonEvents;
- (void)_willAppearInRemoteViewController;

@end

