//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SAUIAssistantUtteranceView, SVSStarkUtteranceSnippetView;

@interface SVSStarkUtteranceSnippetController : UIViewController
{
    SAUIAssistantUtteranceView *_aceObject;
    SVSStarkUtteranceSnippetView *_snippetView;
}

@property(readonly, nonatomic, getter=_snippetView) SVSStarkUtteranceSnippetView *snippetView; // @synthesize snippetView=_snippetView;
@property(readonly, nonatomic, getter=_aceObject) SAUIAssistantUtteranceView *aceObject; // @synthesize aceObject=_aceObject;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithAceObject:(id)arg1;

@end

