//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AceObject, NSSet, NSUUID, SVSSuggestionsViewController, UIView;
@protocol SAAceCommand;

@protocol SVSSuggestionsViewControllerDelegate <NSObject>
- (CDStruct_a82615c4)keyboardInfoForSuggestionsController:(SVSSuggestionsViewController *)arg1;
- (NSSet *)siriEnabledAppListForSuggestionsController:(SVSSuggestionsViewController *)arg1;
- (double)statusViewHeightForSuggestionsViewController:(SVSSuggestionsViewController *)arg1;
- (struct CGRect)statusBarFrameForSuggestionsViewController:(SVSSuggestionsViewController *)arg1;
- (double)contentWidthForSuggestionsViewController:(SVSSuggestionsViewController *)arg1;
- (void)suggestionsViewDidShowSuggestions:(SVSSuggestionsViewController *)arg1;
- (void)suggestionsViewController:(SVSSuggestionsViewController *)arg1 performAceCommand:(AceObject<SAAceCommand> *)arg2 conversationItemIdentifier:(NSUUID *)arg3 completion:(void (^)(_Bool))arg4;

@optional
- (_Bool)inTextInputModeForSuggestionsViewController:(SVSSuggestionsViewController *)arg1;
- (void)suggestionsViewController:(SVSSuggestionsViewController *)arg1 didHideVibrantView:(UIView *)arg2;
@end

