//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface SVSStarkGatekeeperContactView : UIView
{
    UILabel *_nameLabel;
    UIImageView *_photoImageView;
    UIImageView *_appIconImageView;
}

+ (id)associatedDataStore;
@property(readonly, nonatomic, getter=_appIconImageView) UIImageView *appIconImageView; // @synthesize appIconImageView=_appIconImageView;
@property(readonly, nonatomic, getter=_photoImageView) UIImageView *photoImageView; // @synthesize photoImageView=_photoImageView;
@property(readonly, nonatomic, getter=_nameLabel) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)_configureWithDisplayName:(id)arg1 contactPhoto:(id)arg2 contactPhotoURL:(id)arg3 contactIdentifier:(id)arg4 appImage:(id)arg5 nameComponents:(id)arg6;
- (id)initWithMessageIntent:(id)arg1;
- (id)initWithSms:(id)arg1;

@end

