/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 5:03:47 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface FPImageEnumerator : NSObject {

	NSArray* _images;
	unsigned long long _index;

}
-(id)initWithImages:(id)arg1 ;
-(id)nextImageForStart:(unsigned long long)arg1 end:(unsigned long long)arg2 ;
@end

