//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SQLiteMemoryEntity.h"

#import "NSCopying-Protocol.h"

@interface AppEvent : SQLiteMemoryEntity <NSCopying>
{
}

+ (Class)databaseEntityClass;
+ (long long)externalSubtypeForEventType:(unsigned char)arg1;
+ (long long)externalTypeForEventType:(unsigned char)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)timestamp;
- (id)eventKey;
- (id)externalMapping;
- (id)bundleID;
- (id)appMetadata;
- (id)initWithExternalEvent:(id)arg1;
- (id)init;

@end

