//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BaseDatabaseSchema : NSObject
{
}

+ (void)_setUserVersion:(long long)arg1 withConnection:(id)arg2;
+ (void)_applyProtectionClassForDirectoryAtURL:(id)arg1;
+ (_Bool)_addSkipBackupAttribute:(_Bool)arg1 forURL:(id)arg2;
+ (id)tableSQL;
+ (_Bool)resetSchemaIfNeededInDatabaseWithConnection:(id)arg1;
+ (_Bool)resetSchemaIfNeededInDatabase;
+ (id)defaultTableName;
+ (id)setupDatabaseOnce;
+ (id)getConnection;
+ (id)databasePath;
+ (id)databaseName;
+ (void)createSchemaInDatabase;
+ (id)containerURL;
+ (int)currentSchemaVersion;

@end

