//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSNumber;

@interface ClusterKey : NSObject <NSCopying>
{
    NSNumber *_clusterID;
    NSNumber *_clusterVersion;
}

@property(copy, nonatomic) NSNumber *clusterVersion; // @synthesize clusterVersion=_clusterVersion;
@property(copy, nonatomic) NSNumber *clusterID; // @synthesize clusterID=_clusterID;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;

@end

