//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AMSMescalBagContract-Protocol.h"
#import "AMSURLBagContract-Protocol.h"

@class AMSBagValue;

@protocol CrossfireBagContract <AMSURLBagContract, AMSMescalBagContract>
@property(readonly) AMSBagValue *crossfireIncludeLaunches;
@property(readonly) AMSBagValue *crossfireSamplingPercentage;
@property(readonly) AMSBagValue *crossfirePostIntervalSeconds;
@end

