//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NSURLSessionDataDelegatePrivate><NSURLSessionTaskDelegatePrivate;

@interface DownloadTaskState : NSObject
{
    id <NSURLSessionDataDelegatePrivate><NSURLSessionTaskDelegatePrivate> _delegate;
    long long _downloadID;
}

@property long long downloadID; // @synthesize downloadID=_downloadID;
@property __weak id <NSURLSessionDataDelegatePrivate><NSURLSessionTaskDelegatePrivate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;

@end

