//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface FamilyMember : NSObject
{
    _Bool _askToBuy;
    _Bool _me;
    _Bool _sharingPurchases;
    NSString *_iCloudAccountName;
    NSNumber *_iCloudIdentifier;
    NSNumber *_iTunesIdentifier;
    NSString *_firstName;
    NSString *_lastName;
}

@property(nonatomic, getter=isSharingPurchases) _Bool sharingPurchases; // @synthesize sharingPurchases=_sharingPurchases;
@property(nonatomic, getter=isMe) _Bool me; // @synthesize me=_me;
@property(copy, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(copy, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(copy, nonatomic) NSNumber *iTunesIdentifier; // @synthesize iTunesIdentifier=_iTunesIdentifier;
@property(copy, nonatomic) NSNumber *iCloudIdentifier; // @synthesize iCloudIdentifier=_iCloudIdentifier;
@property(copy, nonatomic) NSString *iCloudAccountName; // @synthesize iCloudAccountName=_iCloudAccountName;
@property(nonatomic) _Bool askToBuy; // @synthesize askToBuy=_askToBuy;
- (void).cxx_destruct;
- (id)newCacheRepresentation;
- (id)initWithCacheRepresentation:(id)arg1;
- (id)description;

@end

