//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@class NSString;

@interface NSData (LibAppStoreDaemon)
- (id)lib_gzippedData;
@property(readonly, copy) NSString *lib_shortDigestMD5;
@property(readonly, copy) NSString *lib_digestMD5;
@end

