//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class KeepAlive, NSData, NSDictionary, NSString;

@interface ODRWorkManagedObject : NSManagedObject
{
    KeepAlive *keepAlive;
}

+ (id)_archivedContextClasses;
+ (id)fetchRequest;
@property(retain, nonatomic) KeepAlive *keepAlive; // @synthesize keepAlive;
- (void).cxx_destruct;
- (id)description;
@property(retain, nonatomic) NSDictionary *context;
- (void)markAsCompleted;
- (void)start;

// Remaining properties
@property(copy, nonatomic) NSString *bundleID; // @dynamic bundleID;
@property(retain, nonatomic) NSData *contextData; // @dynamic contextData;
@property(copy, nonatomic) NSString *type; // @dynamic type;

@end

