//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ASDPurchase, XPCRequestToken;

@protocol PurchaseManagerInterface <NSObject>
- (void)startPurchase:(ASDPurchase *)arg1 requestToken:(XPCRequestToken *)arg2 withReplyHandler:(void (^)(ASDPurchaseResult *, NSError *))arg3;
@end

