//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Bulletin.h"

@class NSString;

@interface PurchaseIntentBulletin : Bulletin
{
    NSString *_appBundleId;
}

@property(retain, nonatomic) NSString *appBundleId; // @synthesize appBundleId=_appBundleId;
- (void).cxx_destruct;
- (void)handleCleared;
- (void)handleBulletinActionResponse:(id)arg1;
- (id)newBulletinRequest;
- (id)copyBulletinDictionary;
- (id)initWithBulletinDictionary:(id)arg1;
- (id)init;

@end

