//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface UpdatesBatchRequest : NSObject
{
    NSArray *_apps;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSObject<OS_dispatch_group> *_dispatchGroup;
    NSMutableArray *_updates;
    _Bool _userInitiated;
}

- (void).cxx_destruct;
- (void)_handleUpdatesResponse:(id)arg1;
- (void)_enumerateAppsByAccountUsingBlock:(CDUnknownBlockType)arg1;
- (void)startWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithApps:(id)arg1 userInitiated:(_Bool)arg2;

@end

