/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 5:03:46 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ATLGetDecoder : NSObject
+(Class)getDecoderForApplet:(id)arg1 withPackage:(id)arg2 withModule:(id)arg3 ;
@end

