//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SiriUI/SiriUISnippetViewController.h>

@class SAUIButton, SVSBigButtonView;

@interface SVSBigButtonController : SiriUISnippetViewController
{
    SVSBigButtonView *_buttonView;
    SAUIButton *_buttonObject;
}

- (void).cxx_destruct;
- (void)_bigButtonHit:(id)arg1;
- (double)desiredHeightForWidth:(double)arg1;
- (void)loadView;
- (_Bool)usePlatterStyle;
- (struct UIEdgeInsets)defaultViewInsets;
- (id)snippet;
- (void)setAceObject:(id)arg1;
- (void)dealloc;

@end

