//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SVSStarkItemControllerDelegate-Protocol.h"

@class NSArray, SVSStarkConfirmationSnippetController;

@protocol SVSStarkConfirmationSnippetControllerDelegate <SVSStarkItemControllerDelegate>
- (_Bool)isShowingGatekeeperHeader;
- (void)confirmationSnippetControllerRequestsDismissal:(SVSStarkConfirmationSnippetController *)arg1;
- (void)confirmationSnippetController:(SVSStarkConfirmationSnippetController *)arg1 performAceCommands:(NSArray *)arg2;
@end

