//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, SUICStreamingTextView, SVSTapToEditView;

@interface SVSUserUtteranceView : UIView
{
    struct NSDirectionalEdgeInsets _edgeInsets;
    SUICStreamingTextView *_clonedStreamingTextView;
    SUICStreamingTextView *_streamingTextView;
    _Bool _blendEffectEnabled;
    SVSTapToEditView *_tapToEditView;
    _Bool _chevronHasBeenShown;
    _Bool _editable;
}

+ (double)insertionAnimatedZPosition;
@property(nonatomic, getter=isEditable) _Bool editable; // @synthesize editable=_editable;
- (void).cxx_destruct;
- (double)_scaledSiriTapToEditViewLeading;
- (double)_indentWidth;
- (double)_streamingTextMaxYToTapToEditOriginDistance;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(nonatomic, getter=isBlendEffectEnabled) _Bool blendEffectEnabled;
@property(copy, nonatomic) NSString *text;
- (double)baselineOffsetFromBottom;
- (double)firstLineBaselineOffsetFromTop;
- (void)setChevronHidden:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

