//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BLLibrary;
@protocol BLCacheDeletePurgeableProvider;

__attribute__((visibility("hidden")))
@interface BLCacheDelete : NSObject
{
    BLLibrary *_bookLibrary;
    id <BLCacheDeletePurgeableProvider> _purgeableProvider;
}

+ (void)registerCacheDeleteInfoCallbacks:(CDUnknownBlockType)arg1;
@property(nonatomic) __weak id <BLCacheDeletePurgeableProvider> purgeableProvider; // @synthesize purgeableProvider=_purgeableProvider;
@property(retain, nonatomic) BLLibrary *bookLibrary; // @synthesize bookLibrary=_bookLibrary;
- (void).cxx_destruct;
- (void)_cancelPurge;
- (id)_periodic:(id)arg1 urgency:(int)arg2;
- (id)_purge:(id)arg1 urgency:(int)arg2;
- (id)_purgeable:(id)arg1 urgency:(int)arg2;
- (id)initWithPurgeableProvider:(id)arg1;

@end

