//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CPBitmapStore;

@interface RemindersImageCache : NSObject
{
    CPBitmapStore *_cache;
}

- (void).cxx_destruct;
- (id)imageForKey:(id)arg1 inGroup:(id)arg2;
- (void)setImage:(id)arg1 forKey:(id)arg2 inGroup:(id)arg3;
- (id)initWithName:(id)arg1 versionNumber:(int)arg2;

@end

