//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RemindersCardContentController.h"

@class EKCalendar, NSLayoutConstraint, UIButton, UILabel, UITapGestureRecognizer, UIView;
@protocol RemindersInvitationControllerDelegate;

@interface RemindersInvitationController : RemindersCardContentController
{
    UIView *_dividerLine;
    UILabel *_joinLabel;
    UILabel *_detailLabel;
    UIButton *_declineButton;
    UIButton *_acceptButton;
    UILabel *_loadingLabel;
    NSLayoutConstraint *_labelPaddingConstraint;
    NSLayoutConstraint *_buttonPaddingConstraint;
    UITapGestureRecognizer *_tapGesture;
    EKCalendar *_calendar;
    id <RemindersInvitationControllerDelegate> _delegate;
}

@property(retain) id <RemindersInvitationControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) EKCalendar *calendar; // @synthesize calendar=_calendar;
- (void).cxx_destruct;
- (void)accept;
- (void)decline;
- (id)displayedCalendar;
- (void)setCardState:(unsigned long long)arg1 reloadModelIfNeeded:(_Bool)arg2;
- (void)configureHeaderView:(id)arg1;
- (int)headerViewStyle;
- (void)fontSizeChanged;
- (void)setupConstraints;
- (void)actionLabelTap;
- (void)updateSpamState;
- (void)loadView;

@end

