//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class RemindersListPicker;

@protocol RemindersListPickerDelegate

@optional
- (void)listPickerDidEditCalendars:(RemindersListPicker *)arg1;
- (void)listPickerDidSelect:(RemindersListPicker *)arg1;
- (void)listPickerDidChangeSelectedCalendar:(RemindersListPicker *)arg1;
@end

