//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CPLCloudKitBaseSetupTask.h"

#import "CPLEngineTransportSetupTask-Protocol.h"

@class NSString;
@protocol CPLEngineTransportGroup;

@interface CPLCloudKitSetupTask : CPLCloudKitBaseSetupTask <CPLEngineTransportSetupTask>
{
    CDUnknownBlockType _completionHandler;
    _Bool _shouldUpdateDisabledFeatures;
}

@property(readonly, nonatomic) _Bool shouldUpdateDisabledFeatures; // @synthesize shouldUpdateDisabledFeatures=_shouldUpdateDisabledFeatures;
- (void).cxx_destruct;
- (void)runOperations;
- (void)fetchUserRecord;
- (void)fetchDisabledFeaturesWithUserRecord:(id)arg1;
- (id)initWithController:(id)arg1 updateDisabledFeatures:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;

// Remaining properties
@property(nonatomic, getter=isBackgroundTask) _Bool backgroundTask;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic, getter=isForcedTask) _Bool forcedTask;
@property(nonatomic) _Bool foreground;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isHighPriorityBackground) _Bool highPriorityBackground;
@property(readonly) Class superclass;
@property(retain, nonatomic) id <CPLEngineTransportGroup> transportGroup;

@end

