//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CPLDirectChangeSession.h"

#import "CPLPushChangeSessionImplementation-Protocol.h"

@class CPLEngineLibrary, CPLEnginePushRepository, CPLEngineScheduler, CPLEngineStore, NSMutableSet, NSString;

@interface CPLDirectPushChangeSession : CPLDirectChangeSession <CPLPushChangeSessionImplementation>
{
    _Bool _didPushSomeChange;
    _Bool _pushedBatchesCanLowerQuota;
    NSString *_lastSeenLibraryVersion;
    CPLEngineLibrary *_engineLibrary;
    CPLEngineStore *_store;
    CPLEnginePushRepository *_pushRepository;
    CPLEngineScheduler *_scheduler;
    NSMutableSet *_scopeIdentifiersInThisSession;
}

+ (id)selfCrashResetReason;
- (void).cxx_destruct;
- (void)commitChangeBatch:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)finalizeWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)beginSessionWithKnownLibraryVersion:(id)arg1 context:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)clientWorkDescription;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

