//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CPLEngineStorageImplementation-Protocol.h"

@class CPLScopedIdentifier;

@protocol CPLEngineRemappedDeletesImplementation <CPLEngineStorageImplementation>
- (_Bool)deleteRecordsForScopeIndex:(long long)arg1 maxCount:(long long)arg2 deletedCount:(long long *)arg3 error:(id *)arg4;
- (CPLScopedIdentifier *)realScopedIdentifierForRemappedScopedIdentifier:(CPLScopedIdentifier *)arg1;
- (_Bool)discardDeleteForRemappedRecordWithScopedIdentifier:(CPLScopedIdentifier *)arg1 error:(id *)arg2;
- (_Bool)scheduleDeleteForRemappedRecordWithScopedIdentifier:(CPLScopedIdentifier *)arg1 realScopedIdentifier:(CPLScopedIdentifier *)arg2 asap:(_Bool)arg3 error:(id *)arg4;
@end

