//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CloudPhotoLibrary/CPLPlatformObject.h>

#import "CPLEngineStoreImplementation-Protocol.h"

@class CPLChangeSessionUpdate, CPLPrequeliteVariable, NSDate, NSMutableSet, NSObject, NSString, NSURL, PQLConnection;
@protocol OS_dispatch_queue;

@interface CPLPrequeliteStore : CPLPlatformObject <CPLEngineStoreImplementation>
{
    NSObject<OS_dispatch_queue> *_queue;
    PQLConnection *_db;
    NSURL *_dbURL;
    _Bool _configuringDB;
    NSMutableSet *_modifiedVariables;
    id _globalVariableCacheIdentifier;
    CPLPrequeliteVariable *_libraryVersionVar;
    CPLPrequeliteVariable *_userIdentifierVar;
    CPLPrequeliteVariable *_lastQuarantineCountReportDateVar;
    CPLPrequeliteVariable *_clientCacheIdentifierVar;
    CPLPrequeliteVariable *_clientCacheIdentifierAsKnownByClient;
    CPLPrequeliteVariable *_libraryCreationDateVar;
    CPLPrequeliteVariable *_changeSessionUpdateVar;
    CPLPrequeliteVariable *_libraryOptionsVar;
    CPLPrequeliteVariable *_shouldUpdateDisabledFeaturesVar;
    CPLPrequeliteVariable *_disabledFeaturesDataVar;
    _Bool _versionHasChanged;
    CPLPrequeliteVariable *_deactivatedVar;
    Class _userIdentifierClass;
    NSObject<OS_dispatch_queue> *_isClientInSyncWithClientCacheQueue;
    _Bool _isClientInSyncWithClientCache;
    unsigned long long _resetOption;
    NSString *_resetReason;
    NSString *_wipeReason;
    _Bool _needsToReset;
    _Bool _reentrencyGuard;
    _Bool _didWipeLibrary;
    int _upgradeEventJournal;
    _Bool _mustFix22666940;
    _Bool _mustMigratePushQueue;
    NSDate *_libraryCreationDate;
}

@property(readonly) NSDate *libraryCreationDate; // @synthesize libraryCreationDate=_libraryCreationDate;
- (void).cxx_destruct;
- (_Bool)table:(id)arg1 hasColumnWithName:(id)arg2;
- (void)table:(id)arg1 enumerateCountGroupedByProperty:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)table:(id)arg1 enumerateCountGroupedByUnsignedIntegerProperty:(id)arg2 block:(CDUnknownBlockType)arg3;
- (unsigned long long)table:(id)arg1 countOfRecordsMatchingQuery:(id)arg2;
- (unsigned long long)tableCountOfRecords:(id)arg1;
- (_Bool)table:(id)arg1 hasRecordsMatchingQuery:(id)arg2;
- (_Bool)tableHasRecords:(id)arg1;
- (void)recordUpgradeEvent:(id)arg1 arguments:(struct __va_list_tag [1])arg2;
- (void)recordUpgradeEvent:(id)arg1;
- (id)status;
- (void)writeTransactionDidFail;
- (void)writeTransactionDidSucceed;
- (id)disabledFeatures;
- (_Bool)storeDisabledFeatures:(id)arg1 error:(id *)arg2;
- (_Bool)setShouldUpdateDisabledFeaturesWithError:(id *)arg1;
@property(readonly, nonatomic) _Bool shouldUpdateDisabledFeatures;
- (_Bool)storeChangeSessionUpdate:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) CPLChangeSessionUpdate *storedChangeSessionUpdate;
@property(readonly, nonatomic) _Bool hasStoredChangeSessionUpdate;
- (_Bool)isClientInSyncWithClientCache;
- (_Bool)storeClientIsNotInSyncWithClientCacheWithError:(id *)arg1;
- (_Bool)storeClientIsInSyncWithClientCacheWithError:(id *)arg1;
- (id)createNewClientCacheIdentifier;
- (_Bool)storeClientCacheIdentifier:(id)arg1 error:(id *)arg2;
- (id)clientCacheIdentifier;
- (_Bool)storeLastQuarantineCountReportDate:(id)arg1 error:(id *)arg2;
- (id)lastQuarantineCountReportDate;
- (_Bool)storeUserIdentifier:(id)arg1 error:(id *)arg2;
- (id)userIdentifier;
- (Class)_userIdentifierClass;
- (_Bool)resetValueForGlobalVariable:(id)arg1 error:(id *)arg2;
- (id)valueForGlobalVariable:(id)arg1;
- (_Bool)setValue:(id)arg1 forGlobalVariable:(id)arg2 error:(id *)arg3;
- (_Bool)addGlobalVariable:(id)arg1 defaultValue:(id)arg2 error:(id *)arg3;
- (void)_cacheValue:(id)arg1 forVariable:(id)arg2;
- (id)pqlConnection;
- (id)createNewLibraryVersion;
- (_Bool)storeLibraryVersion:(id)arg1 withError:(id *)arg2;
- (id)libraryVersion;
- (_Bool)updateLibraryOptions:(unsigned long long)arg1 error:(id *)arg2;
- (unsigned long long)libraryOptions;
- (void)performBarrier;
- (void)performBarrierTransaction:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (_Bool)closeWithError:(id *)arg1;
- (void)performWriteTransaction:(id)arg1 withBlock:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)performReadTransaction:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (_Bool)executePostOpenWithError:(id *)arg1;
- (_Bool)openWithError:(id *)arg1;
- (_Bool)_openWithError:(id *)arg1;
- (_Bool)_setupPragmasAndFunctions;
- (_Bool)markDatabaseAsDeactivatedWithError:(id *)arg1;
@property(readonly, nonatomic) id corruptionInfo;
- (_Bool)_setupDBIfNeeded;
- (_Bool)_upgradeDB:(long long)arg1;
- (_Bool)_wipeIfNecessary:(long long)arg1;
- (_Bool)_postUpgradeToVersion:(long long)arg1;
- (_Bool)_upgradeToVersion:(long long)arg1;
- (_Bool)_fix22666940;
- (_Bool)_initializeDB;
- (void)triggerResetAfterUpgrade:(unsigned long long)arg1 withReason:(id)arg2;
- (id)initWithAbstractObject:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

