//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iTunesStoreUI/SUNavigationItem.h>

@protocol ServiceBridgedNavigationItemProxy;

@interface ServiceBridgedNavigationItem : SUNavigationItem
{
    id <ServiceBridgedNavigationItemProxy> _proxyHandler;
}

+ (id)itemFromItem:(id)arg1;
@property(nonatomic) __weak id <ServiceBridgedNavigationItemProxy> proxyHandler; // @synthesize proxyHandler=_proxyHandler;
- (void).cxx_destruct;
- (void)setRightBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (void)setTitle:(id)arg1;

@end

