//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIImageView, UILabel;

@interface COSPhoneView : UIView
{
    long long _style;
    UIImageView *_deviceImageView;
    UIImageView *_screenImageView;
    NSString *_screenImageName;
    UILabel *_internalErrorLabel;
}

@property(retain, nonatomic) UILabel *internalErrorLabel; // @synthesize internalErrorLabel=_internalErrorLabel;
@property(copy, nonatomic) NSString *screenImageName; // @synthesize screenImageName=_screenImageName;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1;

@end

