//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COSOptinViewController.h"

#import "COSBuddyController-Protocol.h"
#import "PBAutomationDocumentation-Protocol.h"

@class NSString;

@interface COSUnifiedOptinFYIViewController : COSOptinViewController <PBAutomationDocumentation, COSBuddyController>
{
}

+ (_Bool)hasTelephonyAndIsGreenTea;
+ (id)radarComponent;
+ (id)documentationDescription;
+ (id)subViews;
+ (id)viewsAndActions;
+ (_Bool)controllerNeedsToRun;
- (void)okayButtonPressed:(id)arg1;
- (double)okayButtonTopPadding;
- (double)imageDetailPadding;
- (double)sidePadding;
- (id)detailAtrributedString;
- (id)detailTitleString;
- (id)alternateButtonTitle;
- (id)okayButtonTitle;
- (id)imageResource;
- (id)titleString;
- (_Bool)legacyButtonStyles;
- (_Bool)wantsLightenBlendedScreen;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

