//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtCC5Files17CloudStatsTracker18UploadProgressStat : SwiftObject
{
    // Error parsing type: , name: tracker
    // Error parsing type: , name: value
    // Error parsing type: , name: subscriptionToken
    // Error parsing type: , name: completedFileCountObserver
    // Error parsing type: , name: totalFileCountObserver
}

@end

