//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC5Files24DOCRecentsViewController.h"

@interface _TtC5Files24DOCRecentsViewController (Files2)
- (void)collectionView:(id)arg1 prefetchItemsAtIndexPaths:(id)arg2;
@end

