//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIViewControllerTransitioningDelegate-Protocol.h"

@interface _TtC5FilesP33_03C5E21A9DFBF0EC7F1C3AC78C186A7532DOCFilenameTransitioningDelegate : NSObject <UIViewControllerTransitioningDelegate>
{
    // Error parsing type: , name: browserProxy
    // Error parsing type: , name: transitioningController
}

- (CDUnknownBlockType).cxx_destruct;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)init;

@end

