//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC5Files29DOCItemCollectionLayoutTraits : SwiftObject
{
    // Error parsing type: , name: gridLayoutTraits.storage
    // Error parsing type: , name: gridItemLayoutTraits.storage
    // Error parsing type: , name: gridItemBadgeLayoutTraits.storage
    // Error parsing type: , name: listLayoutTraits.storage
    // Error parsing type: , name: listItemLayoutTraits.storage
    // Error parsing type: , name: context
    // Error parsing type: , name: traitCollection
    // Error parsing type: , name: containerViewSize
    // Error parsing type: , name: itemCount
    // Error parsing type: , name: gridSpecs
    // Error parsing type: , name: listSpecs
}

@end

