//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC5Files40DOCServiceDocumentProviderViewController.h"

#import "FPUIActionViewControllerDelegate-Protocol.h"

@interface _TtC5Files29DOCFileProviderViewController : _TtC5Files40DOCServiceDocumentProviderViewController <FPUIActionViewControllerDelegate>
{
    // Error parsing type: , name: fileProviderConfiguration
    // Error parsing type: , name: urlToItemCache
    // Error parsing type: , name: itemCollectionViewController
    // Error parsing type: , name: lastSelectedItem
    // Error parsing type: , name: lastOpenedItem
    // Error parsing type: , name: interactionDelegate
    // Error parsing type: , name: testingDelegate
    // Error parsing type: , name: isCurrentLocationWritable
    // Error parsing type: , name: collectionHasFinishedGatheringItemsAndThumbnails
    // Error parsing type: , name: currentLocationCanSelect
    // Error parsing type: , name: errorRecoveryContext
    // Error parsing type: , name: appearance
    // Error parsing type: , name: selectedItems
    // Error parsing type: , name: currentItems
    // Error parsing type: , name: customFileProviderActions
    // Error parsing type: , name: customFileProviderUIActions
    // Error parsing type: , name: copyAction.storage
    // Error parsing type: , name: duplicateAction.storage
    // Error parsing type: , name: favoriteAction.storage
    // Error parsing type: , name: unfavoriteAction.storage
    // Error parsing type: , name: mixedDeleteAction.storage
    // Error parsing type: , name: finishGatheringObserver
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)actionControllerDidFinishAction:(id)arg1 error:(id)arg2;
- (void)itemCollection:(id)arg1 perform:(id)arg2 on:(id)arg3;
- (id)itemCollection:(id)arg1 actionsFor:(id)arg2;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateAppearance:(id)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

