//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC5Files23DOCRecentsRowHeaderView : UIView
{
    // Error parsing type: , name: titleLabel.storage
    // Error parsing type: , name: seeAllButton.storage
    // Error parsing type: , name: invisibleRowHeight.storage
    // Error parsing type: , name: seeAllButtonVisibleConstraint.storage
    // Error parsing type: , name: regularConstraints
    // Error parsing type: , name: largeTextConstraints
    // Error parsing type: , name: tagColor
    // Error parsing type: , name: title
    // Error parsing type: , name: showSeeAllButton
}

- (CDUnknownBlockType).cxx_destruct;
- (id)accessibilityTitleLabel;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool hidden;
- (_Bool)isHidden;

@end

