//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC5Files31DOCItemCollectionViewController.h"

#import "UIViewControllerPreviewingDelegate-Protocol.h"

@interface _TtC5Files31DOCItemCollectionViewController (Files) <UIViewControllerPreviewingDelegate>
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
@end

