//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CalendarMessageCell.h"

@class EKCalendarEventInvitationNotification, NSString;

@interface CalendarMessageEventInvitationCell : CalendarMessageCell
{
    NSString *_organizerString;
    NSString *_invitedByString;
    NSString *_dateString;
    NSString *_organizerName;
}

@property(retain, nonatomic) NSString *organizerName; // @synthesize organizerName=_organizerName;
- (void).cxx_destruct;
@property(retain, nonatomic) EKCalendarEventInvitationNotification *notification; // @dynamic notification;
- (_Bool)notificationIsInvite;
- (_Bool)notificationIsCancelled;
- (_Bool)showAsCancelledOrDeclined;
- (id)actions;
- (id)_locationString;
- (id)_dateString;
- (id)_organizerString;
- (id)_invitedByString;
- (void)updateAuthor;
- (long long)selectedResponseButton;
- (long long)actionBodyStringAction;
- (id)actionBodyString;
- (id)preActionBodyStrings;
- (id)bodyStrings;
- (id)titleStrings;

@end

