//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YearViewYearHeader.h"

@interface CompactYearViewYearHeader : YearViewYearHeader
{
}

+ (double)headerDaySpacing;
+ (double)middleHeight;
+ (double)headerYInset;
- (double)overlayLegendMonthLineThickness;
- (double)overlayLegendYearLineThickness;
- (double)overlayLegendLineLength;
- (double)overlayLegendSpacing;
- (double)overlayLegendMonthBaseline;
- (double)overlayLegendYearBaseline;
- (double)overlayLegendRightInset;
- (id)overlayLegendFont;
- (double)yearNumberKerning;
- (id)yearNumberFont;
- (double)heightBetweenLineAndNumber;

@end

