//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FutureTraitEnvironment-Protocol.h"
#import "NSObject-Protocol.h"

@class EKCalendarDate, NSAttributedString, NSString, PaletteView, UIColor;

@protocol MainViewControllerOptionalMethods <NSObject, FutureTraitEnvironment>

@optional
@property(readonly, nonatomic) _Bool shouldAdaptEventViewControllers;
@property(nonatomic) _Bool isWaitingForBackgroundLoadingOfSelectedEventOccurrenceView;
- (_Bool)currentlyEditingEventsWithGestures;
- (_Bool)isTodayVisible;
- (void)setShouldRespondToApplicationDidBecomeActiveStateChange:(_Bool)arg1;
- (_Bool)shouldRespondToApplicationDidBecomeActiveStateChange;
- (NSString *)updateBackButtonWhileTopViewControllerToDate:(EKCalendarDate *)arg1;
- (_Bool)shouldUpdateOwnBackButtonWhenTopViewController;
- (void)updateBackButtonToDate:(EKCalendarDate *)arg1;
- (void)invalidateBackButtonDate;
- (void)updateNavigationBarDisplayedDateString;
- (NSAttributedString *)navigationBarDisplayedDateString;
- (int)supportedToggleMode;
- (UIColor *)toolBarTintColor;
- (UIColor *)navigationBarTintColor;
- (_Bool)showEventDetailsWhenNewEventAdded;
- (EKCalendarDate *)bestDateForNewEvent;
- (void)updatePalette:(PaletteView *)arg1;
- (double)leftBarButtonBlankFixedSpaceWidth;
- (void)disableGestureRecognizers;
- (void)enableGestureRecognizers;
- (_Bool)shouldPushNextLevelViewControllerWhenTodayIsVisible;
- (void)showNowAnimated:(_Bool)arg1;
@end

