//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FutureTraitEnvironment-Protocol.h"

@class NSString, UITraitCollection;

@interface UIViewController (MobileCalExtendedUIViewControllerProperties) <FutureTraitEnvironment>
@property(retain, nonatomic) UITraitCollection *futureTraitCollection;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isTransitioningTraitCollection;
@property(readonly) Class superclass;
@property(readonly, nonatomic) UITraitCollection *traitCollection;
@end

