/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:57:44 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libBasebandManagerICE.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CMCallHandednessDelegate <NSObject>
@required
-(void)callHandednessManager:(id)arg1 didUpdateState:(long long)arg2;

@end

