//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FRStateRestoreCoordinating-Protocol.h"
#import "UIStateRestoring-Protocol.h"

@class FRArticlePageViewController, FRArticleViewHeadlineContext, UIViewController;

@protocol FRArticlePageViewDataSource <UIStateRestoring, FRStateRestoreCoordinating>
- (UIViewController *)articlePageViewController:(FRArticlePageViewController *)arg1 viewControllerWithHeadlineContext:(FRArticleViewHeadlineContext *)arg2 preloading:(_Bool)arg3;
- (FRArticleViewHeadlineContext *)articlePageViewController:(FRArticlePageViewController *)arg1 headlineBeforeHeadlineContext:(FRArticleViewHeadlineContext *)arg2;
- (FRArticleViewHeadlineContext *)articlePageViewController:(FRArticlePageViewController *)arg1 headlineAfterHeadlineContext:(FRArticleViewHeadlineContext *)arg2;
- (unsigned long long)numberOfArticlesForArticlePageViewController:(FRArticlePageViewController *)arg1;
@end

