//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FRBarCompressor;

@protocol FRBarCompressorDelegate <NSObject>

@optional
- (void)barCompressor:(FRBarCompressor *)arg1 didChangeToState:(long long)arg2;
- (void)barCompressorScrollViewDidDragDown:(FRBarCompressor *)arg1;
- (void)barCompressorScrollViewDidDragUp:(FRBarCompressor *)arg1;
- (void)barCompressorScrollViewDidScrollOffTop:(FRBarCompressor *)arg1;
- (void)barCompressorScrollViewDidHitTop:(FRBarCompressor *)arg1;
@end

