//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class FREditorialManager, UITextView;

@interface FRDebugEditorialArticleViewController : UIViewController
{
    FREditorialManager *_editorialManager;
    UITextView *_informationView;
}

@property(retain, nonatomic) UITextView *informationView; // @synthesize informationView=_informationView;
@property(retain, nonatomic) FREditorialManager *editorialManager; // @synthesize editorialManager=_editorialManager;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithEditorialManager:(id)arg1;

@end

