//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FRInteractiveBarCompressionAnimating-Protocol.h"

@class FRAnimationFloatFunction, NUFeedTitleView, UINavigationBar, UIView;

@interface FRForYouNavigationBarCompressionAnimation : NSObject <FRInteractiveBarCompressionAnimating>
{
    _Bool _titleViewUpdating;
    _Bool _scrollViewCurrentlyAtTop;
    _Bool _wasLastScrollUpscroll;
    double _topOffset;
    UINavigationBar *_navigationBar;
    NUFeedTitleView *_titleView;
    UIView *_maskView;
    FRAnimationFloatFunction *_opacityFunction;
    FRAnimationFloatFunction *_scaleFunction;
    FRAnimationFloatFunction *_translateFunction;
}

@property(nonatomic) _Bool wasLastScrollUpscroll; // @synthesize wasLastScrollUpscroll=_wasLastScrollUpscroll;
@property(nonatomic, getter=isScrollViewCurrentlyAtTop) _Bool scrollViewCurrentlyAtTop; // @synthesize scrollViewCurrentlyAtTop=_scrollViewCurrentlyAtTop;
@property(retain, nonatomic) FRAnimationFloatFunction *translateFunction; // @synthesize translateFunction=_translateFunction;
@property(retain, nonatomic) FRAnimationFloatFunction *scaleFunction; // @synthesize scaleFunction=_scaleFunction;
@property(retain, nonatomic) FRAnimationFloatFunction *opacityFunction; // @synthesize opacityFunction=_opacityFunction;
@property(readonly, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) NUFeedTitleView *titleView; // @synthesize titleView=_titleView;
@property(readonly, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(nonatomic, getter=isTitleViewUpdating) _Bool titleViewUpdating; // @synthesize titleViewUpdating=_titleViewUpdating;
@property(nonatomic) double topOffset; // @synthesize topOffset=_topOffset;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool prefersCompressedStyling;
- (void)reloadWithTraitCollection:(id)arg1;
@property(readonly, nonatomic) _Bool closeGapWhenCompressed;
@property(readonly, nonatomic) _Bool shouldCompressAtTop;
- (void)scrollViewIsAtTop:(_Bool)arg1;
- (void)scrollViewDidDragDown;
- (void)scrollViewDidDragUp;
- (_Bool)animationShouldBeginForScrollView:(id)arg1 currentlyFullyCompressed:(_Bool)arg2;
- (double)minimumBarHeightForTraitCollection:(id)arg1;
- (double)maximumBarHeightForTraitCollection:(id)arg1;
- (void)updateWithPercentage:(double)arg1;
- (id)initWithNavigationBar:(id)arg1 titleView:(id)arg2;

@end

