//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, UINavigationBar, UIScrollView;
@protocol FRNavigationBarHeightUpdateThrottler, TSInteractiveBarCompressionAnimating;

@interface FRNavigationBarCompressor : NSObject <UIScrollViewDelegate>
{
    _Bool _compressionEnabled;
    _Bool _nonInteractiveScrollIsInProgress;
    UINavigationBar *_navigationBar;
    id <TSInteractiveBarCompressionAnimating> _compressionAnimator;
    UIScrollView *_scrollView;
    id <FRNavigationBarHeightUpdateThrottler> _updateThrottler;
}

@property(nonatomic, getter=isNonInteractiveScrollInProgress) _Bool nonInteractiveScrollIsInProgress; // @synthesize nonInteractiveScrollIsInProgress=_nonInteractiveScrollIsInProgress;
@property(retain, nonatomic) id <FRNavigationBarHeightUpdateThrottler> updateThrottler; // @synthesize updateThrottler=_updateThrottler;
@property(nonatomic, getter=isCompressionEnabled) _Bool compressionEnabled; // @synthesize compressionEnabled=_compressionEnabled;
@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) id <TSInteractiveBarCompressionAnimating> compressionAnimator; // @synthesize compressionAnimator=_compressionAnimator;
@property(readonly, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
- (void).cxx_destruct;
- (double)_compressionProgress;
- (void)_updateTargetBarHeightIfNeededForCompressionProgress:(double)arg1;
- (void)_updateAnimatorWithCompressionProgress:(double)arg1;
- (void)_updateThrottlerProgressForScrollViewContentOffset;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_installUpdateThrottler;
- (void)_uninstallUpdateThrottler;
- (void)setNavigationBarHeight:(double)arg1;
- (void)reloadWithTraitCollection:(id)arg1;
@property(readonly, nonatomic) _Bool inCompressionRange;
- (id)initWithCompressionAnimator:(id)arg1 scrollView:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

