//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSUserDefaults.h>

@interface NSUserDefaults (FRAdditions)
- (id)numberOfTimesUserHasConfirmedMute;
- (void)setNumberOfTimesUserHasConfirmedMute:(id)arg1;
- (_Bool)shouldShowHUDInsteadOfMuteConfirmation;
- (void)setShouldShowHUDInsteadOfMuteConfirmation:(_Bool)arg1;
- (_Bool)hasReachedMaxNumberOfTimesUserHasConfirmedMute;
- (void)incrementNumberOfTimesUserHasConfirmedMute;
@end

