//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, TSArticleContext, UIViewController;
@protocol FCHeadlineProviding;

@protocol TSArticleViewerModuleType
- (UIViewController *)createViewControllerForArticleID:(NSString *)arg1 headline:(id <FCHeadlineProviding>)arg2 articleContext:(TSArticleContext *)arg3 notificationSenderChannelID:(NSString *)arg4 articlePresentationStyle:(long long)arg5 showShareSheet:(_Bool)arg6 forceArticleUpdate:(_Bool)arg7 presentingEditorialArticle:(_Bool)arg8;
@end

