//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString;

@protocol TSPurchaseContext
@property(readonly, nonatomic) _Bool sawSubscriptionSheet;
@property(readonly, nonatomic) _Bool arrivedFromAd;
@property(readonly, nonatomic) _Bool fromSubscriptionOnlyArticle;
@property(readonly, nonatomic) long long parentFeedType;
@property(readonly, copy, nonatomic) NSString *purchaseSessionID;
@property(readonly, copy, nonatomic) NSString *feedViewExposureID;
@property(readonly, copy, nonatomic) NSString *articleViewingSessionID;
@property(readonly, copy, nonatomic) NSString *adCampaignID;
@property(readonly, copy, nonatomic) NSString *qToken;
@property(readonly, copy, nonatomic) NSString *sectionID;
@property(readonly, copy, nonatomic) NSString *articleID;
@property(readonly, copy, nonatomic) NSString *sourceChannelID;
@property(readonly, nonatomic) long long subscriptionConversionPointType;
@end

