//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AudioSettingsTableViewCell;

__attribute__((visibility("hidden")))
@interface AudioSettingTableRow : NSObject
{
    AudioSettingsTableViewCell *_currentCell;
}

@property(readonly, nonatomic) AudioSettingsTableViewCell *currentCell; // @synthesize currentCell=_currentCell;
- (void).cxx_destruct;
- (void)configureCurrentCellWithConfiguration:(id)arg1;
- (id)updateCurrentCellForTableView:(id)arg1 configuration:(id)arg2;
- (id)reuseIdentifierForCell;

@end

