//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, SearchSession;
@protocol CarDestinationsTab;

@protocol CarDestinationsTabDelegate <NSObject>
- (SearchSession *)searchSessionForDestinationsTab:(id <CarDestinationsTab>)arg1;
- (void)destinationsTab:(id <CarDestinationsTab>)arg1 wantsToShowResults:(NSArray *)arg2;
- (void)destinationsTab:(id <CarDestinationsTab>)arg1 didChangeLoading:(_Bool)arg2;
@end

