//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CarWaypointsController.h"

__attribute__((visibility("hidden")))
@interface CarExistingWaypointsController : CarWaypointsController
{
}

- (_Bool)shouldStartLoadWhenBecomingCurrent;
- (id)_waypoint;
- (id)_address;
- (id)_titleOrName;
- (id)subtitleForCurrentDestination;
- (_Bool)hasBothTitleAndAddress;
- (id)titleForCurrentDestination;

@end

