//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CarChromeModeController-Protocol.h"

@class CarAlertViewController, CarChromeViewController, ChromeViewController, NSString;

__attribute__((visibility("hidden")))
@interface CarIncompatibleNavigationModeController : NSObject <CarChromeModeController>
{
    CarAlertViewController *_viewController;
    CarChromeViewController *_chromeViewController;
}

@property(nonatomic) ChromeViewController *chromeViewController;
- (void).cxx_destruct;
- (void)resignCurrentModeAnimated:(_Bool)arg1 toMode:(id)arg2;
- (void)becomeCurrentModeWithViews:(id)arg1 animated:(_Bool)arg2 state:(id)arg3 fromMode:(id)arg4;
- (void)configureNavigationDisplay:(id)arg1;
- (id)transitionControllerForPopToMode:(id)arg1;
- (id)transitionControllerForPushFromMode:(id)arg1;
- (_Bool)usesDefaultTransitions;
- (_Bool)shouldAllowKnobFocusMovement;
- (_Bool)showsMapView;
- (_Bool)showsNavigationBar;
- (id)viewController;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

