//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CarBaseSearchResultsViewController.h"

@class CarKeyboardSearchModeController;

__attribute__((visibility("hidden")))
@interface CarKeyboardSearchResultsController : CarBaseSearchResultsViewController
{
    CarKeyboardSearchModeController *_container;
}

@property(nonatomic) __weak CarKeyboardSearchModeController *container; // @synthesize container=_container;
- (void).cxx_destruct;
- (void)pushDetailsForItemSelectedAtIndexPath:(id)arg1;
- (id)itemAtIndexPath:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;

@end

