//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CarManeuverView, NSUUID;

@protocol CarManeuverViewAnalyticsDelegate
- (void)carManeuverView:(CarManeuverView *)arg1 didSelectAlternate:(unsigned long long)arg2 forPrimaryString:(_Bool)arg3 inSign:(NSUUID *)arg4;
@end

