//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIFont, UILabel;

__attribute__((visibility("hidden")))
@interface CarNavigationDistanceLabel : UIView
{
    UILabel *_primaryLabel;
    UILabel *_secondaryLabel;
    double _remainingDistance;
    long long _detail;
    UIFont *_topFont;
    UIFont *_bottomFont;
}

@property(retain, nonatomic) UIFont *bottomFont; // @synthesize bottomFont=_bottomFont;
@property(retain, nonatomic) UIFont *topFont; // @synthesize topFont=_topFont;
@property(nonatomic) long long detail; // @synthesize detail=_detail;
@property(nonatomic) double remainingDistance; // @synthesize remainingDistance=_remainingDistance;
- (void).cxx_destruct;
- (struct UIEdgeInsets)alignmentRectInsets;
- (void)_updateValues;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (double)_labelOffset;
- (void)_updateStyling;
- (id)initWithFrame:(struct CGRect)arg1;

@end

