//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CarChromeViewController, GEOComposedRoute, GEORouteMatch, MKMapItem, VKPolylineOverlay;

__attribute__((visibility("hidden")))
@interface CarRouteGeniusAnnotationsManager : NSObject
{
    VKPolylineOverlay *_routeLine;
    CarChromeViewController *_chromeViewController;
    GEOComposedRoute *_route;
    GEORouteMatch *_match;
    MKMapItem *_destination;
}

@property(retain, nonatomic) MKMapItem *destination; // @synthesize destination=_destination;
@property(retain, nonatomic) GEORouteMatch *match; // @synthesize match=_match;
@property(retain, nonatomic) GEOComposedRoute *route; // @synthesize route=_route;
@property(nonatomic) __weak CarChromeViewController *chromeViewController; // @synthesize chromeViewController=_chromeViewController;
- (void).cxx_destruct;
- (id)mapView;
- (id)mapViewCurrentRouteMatch:(id)arg1;
- (void)clearAnnotations;
- (void)_drawRoute:(id)arg1;
- (void)_eraseRoute:(id)arg1;
- (void)recenterCameraOnRouteAnimated:(_Bool)arg1;

@end

