//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CarWaypointsController.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface CarSearchWaypointsController : CarWaypointsController
{
    NSArray *_results;
    unsigned long long _selectedIndex;
}

@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(readonly, copy, nonatomic) NSArray *results; // @synthesize results=_results;
- (void).cxx_destruct;
- (unsigned long long)totalDestinations;
- (unsigned long long)indexOfCurrentDestination;
- (id)subtitleForCurrentDestination;
- (id)titleForCurrentDestination;
- (id)destinationWaypoint;
- (id)visuallySelectedItem;
- (void)previousPlaceWithTraits:(id)arg1;
- (void)nextPlaceWithTraits:(id)arg1;
- (id)destinationSearchResultIfAvailable;
- (id)initWithSearchResults:(id)arg1 selectedIndex:(unsigned long long)arg2;

@end

