//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CarMapTrackingController, CarUIBarButtonItemsController, MKMapView;

@protocol CarUIBarButtonItemsControllerDelegate <NSObject>
@property(readonly) MKMapView *mapView;

@optional
@property(readonly) CarMapTrackingController *trackingController;
- (_Bool)toggle3DButtonIsSelected;
- (void)buttonController:(CarUIBarButtonItemsController *)arg1 didSelectItem:(unsigned long long)arg2;
- (_Bool)buttonController:(CarUIBarButtonItemsController *)arg1 shouldShowItem:(unsigned long long)arg2;
@end

