//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class GEOSearchCategory, NSString;

__attribute__((visibility("hidden")))
@interface CategoryKey : NSObject <NSCopying>
{
    _Bool _transitMode;
    _Bool _isCarPlay;
    GEOSearchCategory *_category;
    NSString *_prefix;
    double _scale;
    struct CGSize _size;
}

@property(nonatomic) _Bool isCarPlay; // @synthesize isCarPlay=_isCarPlay;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(nonatomic) _Bool transitMode; // @synthesize transitMode=_transitMode;
@property(copy, nonatomic) NSString *prefix; // @synthesize prefix=_prefix;
@property(retain, nonatomic) GEOSearchCategory *category; // @synthesize category=_category;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;

@end

