//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIImage;

@protocol CollectionViewViewModel <NSObject>
@property(readonly, nonatomic) unsigned long long numberOfItems;
- (void)refreshViewModelWithCompletion:(void (^)(_Bool))arg1;
- (long long)imageViewContentModeForItemAtIndex:(unsigned long long)arg1;
- (_Bool)requireCustomImageBackgroundColorForItemAtIndex:(unsigned long long)arg1;
- (void)itemDidSelectAtIndex:(unsigned long long)arg1;
- (UIImage *)imageForItemAtIndex:(unsigned long long)arg1;
- (NSString *)titleForItemAtIndex:(unsigned long long)arg1;
@end

