//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UIScrollViewDelegate-Protocol.h"

@class DataSource, SearchResult;

@protocol DataSourceDelegate <UIScrollViewDelegate>
- (void)dataSource:(DataSource *)arg1 itemTapped:(id)arg2;
- (void)dataSourceUpdated:(DataSource *)arg1;

@optional
- (int)listForDataSource:(DataSource *)arg1;
- (void)dataSource:(DataSource *)arg1 searchResultNeedsEditing:(SearchResult *)arg2 completion:(void (^)(void))arg3;
@end

