//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ErrorActionOption : NSObject
{
    _Bool _cancels;
    NSString *_title;
    CDUnknownBlockType _handler;
}

@property(readonly, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(readonly, nonatomic) _Bool cancels; // @synthesize cancels=_cancels;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 cancels:(_Bool)arg2 handler:(CDUnknownBlockType)arg3;

@end

