//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SearchDataSource.h"

@class MapsTheme;

__attribute__((visibility("hidden")))
@interface FavoritesSearchDataSource : SearchDataSource
{
    MapsTheme *_mapsTheme;
}

- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)initWithTableView:(id)arg1 mapsTheme:(id)arg2;

@end

