//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FlyoverGlyphView, NSLayoutConstraint, UILabel, UIVisualEffectView;

__attribute__((visibility("hidden")))
@interface FlyoverStatusToastView : UIView
{
    UIVisualEffectView *_backgroundView;
    FlyoverGlyphView *_glyphView;
    UILabel *_label;
    NSLayoutConstraint *_backgroundTopConstraint;
    NSLayoutConstraint *_backgroundLeftConstraint;
    NSLayoutConstraint *_backgroundBottomConstraint;
    NSLayoutConstraint *_backgroundRightConstraint;
    _Bool _didPresent;
    _Bool _didDismiss;
}

+ (struct CGSize)preferredSize;
@property(readonly, nonatomic) _Bool didDismiss; // @synthesize didDismiss=_didDismiss;
@property(readonly, nonatomic) _Bool didPresent; // @synthesize didPresent=_didPresent;
- (void).cxx_destruct;
- (void)dismissWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)present;
- (id)initWithTrackingStateReason:(unsigned long long)arg1;

@end

