//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AppCoordination-Protocol.h"
#import "FlyoverContainerViewControllerDelegate-Protocol.h"

@class UIViewController;

@protocol FlyoverActionCoordination <AppCoordination, FlyoverContainerViewControllerDelegate>
@property(readonly, nonatomic, getter=isFlyoverRunning) _Bool flyoverRunning;
- (void)flyoverTourCompleted;
- (void)flyoverTourResume;
- (void)flyoverTourPause;
- (void)flyoverTourPlay;
- (void)updateViewMode:(long long)arg1 animated:(_Bool)arg2;
- (long long)displayedViewMode;
- (void)viewControllerPresentTray:(UIViewController *)arg1;
- (void)viewControllerEndFlyover:(UIViewController *)arg1;
@end

