//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsThemeView.h"

@class NSLayoutConstraint, UIActivityIndicatorView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface LoadingModeView : MapsThemeView
{
    UIActivityIndicatorView *_activityView;
    UILabel *_titleLabel;
    UIView *_contentView;
    NSLayoutConstraint *_bottomContentConstraint;
}

- (void).cxx_destruct;
- (void)setupConstraints;
- (void)setBottomInset:(double)arg1;
- (id)initWithTitle:(id)arg1;
- (void)updateTheme;

@end

