//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsAppTest.h"

__attribute__((visibility("hidden")))
@interface MapsAppTestJump : MapsAppTest
{
    _Bool _savedDebugDrawContinuously;
    double _pitch;
    double _yaw;
    CDStruct_071ac149 _endPoint;
}

@property(nonatomic) _Bool savedDebugDrawContinuously; // @synthesize savedDebugDrawContinuously=_savedDebugDrawContinuously;
@property(nonatomic) double yaw; // @synthesize yaw=_yaw;
@property(nonatomic) double pitch; // @synthesize pitch=_pitch;
@property(nonatomic) CDStruct_39925896 endPoint; // @synthesize endPoint=_endPoint;
- (void)finishedFps;
- (void)startTimingFps;
- (void)didFinishJumping;
- (void)jumpToCupertino;
- (void)jumpToBayArea;
- (_Bool)runTest;
- (id)initWithApplication:(id)arg1 testName:(id)arg2 options:(id)arg3;

@end

