//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GEOPlaceActionDetails, NSString;

__attribute__((visibility("hidden")))
@interface MapsAnalyticsHelper : NSObject
{
    int _tapAction;
    int _target;
    GEOPlaceActionDetails *_actionDetails;
    NSString *_eventValue;
}

@property(readonly, nonatomic) NSString *eventValue; // @synthesize eventValue=_eventValue;
@property(readonly, nonatomic) GEOPlaceActionDetails *actionDetails; // @synthesize actionDetails=_actionDetails;
@property(readonly, nonatomic) int target; // @synthesize target=_target;
@property(readonly, nonatomic) int tapAction; // @synthesize tapAction=_tapAction;
- (void).cxx_destruct;
- (id)initWithMapItem:(id)arg1;
- (id)initWithLabelMarker:(id)arg1;
- (id)init;

@end

