//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Navigation/MNCommuteDestination.h>

@class GuidanceETA, MKMapItem, MapsSuggestionsEntry, NSDate;

@interface MNCommuteDestination (MapsExtras)
+ (id)__debug_fakeCommuteDestination;
- (void)removeMapsExtrasObserver:(id)arg1;
- (void)addMapsExtrasObserver:(id)arg1;
@property(readonly) MKMapItem *MKMapItem;
@property(readonly) GuidanceETA *guidanceETA;
@property(readonly) long long mapsSuggestionsEntryType;
@property(readonly) MapsSuggestionsEntry *mapsSuggestionEntry;

// Remaining properties
@property(readonly) NSDate *displayETA;
@property(readonly) double displayRemainingTime;
@end

