//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NavigationChromeViewItem;
@protocol UIViewControllerAnimatedTransitioning;

__attribute__((visibility("hidden")))
@interface NavigationChromeTransitionContext : NSObject
{
    NavigationChromeViewItem *_toItem;
    NavigationChromeViewItem *_fromItem;
    id <UIViewControllerAnimatedTransitioning> _customTransition;
}

@property(retain, nonatomic) id <UIViewControllerAnimatedTransitioning> customTransition; // @synthesize customTransition=_customTransition;
@property(retain, nonatomic) NavigationChromeViewItem *fromItem; // @synthesize fromItem=_fromItem;
@property(retain, nonatomic) NavigationChromeViewItem *toItem; // @synthesize toItem=_toItem;
- (void).cxx_destruct;
- (id)description;

@end

