//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;
@protocol NavigationCameraSnapshotsObserver;

__attribute__((visibility("hidden")))
@interface NavigationCameraSnapshotManager : NSObject
{
    NSString *_archivePath;
    NSMutableDictionary *_traceSnapshotsDictionary;
    id <NavigationCameraSnapshotsObserver> _snapshotsObserver;
}

+ (_Bool)archiveTraceSnapshotsDictionary:(id)arg1 toFile:(id)arg2;
+ (id)traceSnapshotsDictionaryWithContentsOfArchiveFile:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic) __weak id <NavigationCameraSnapshotsObserver> snapshotsObserver; // @synthesize snapshotsObserver=_snapshotsObserver;
- (void).cxx_destruct;
- (CDUnknownBlockType)_cameraSnapshotComparator;
- (void)_commitTraceSnapshotsDictionaryToArchive;
- (void)removeCameraSnapshotAtIndex:(unsigned long long)arg1 fromTraceFile:(id)arg2;
- (void)addCameraSnapshot:(id)arg1 toTraceFile:(id)arg2;
- (id)cameraSnapshotsOfTraceFile:(id)arg1;
@property(readonly, nonatomic) NSMutableDictionary *traceSnapshotsDictionary;
@property(readonly, nonatomic) NSString *archivePath;
- (id)initWithTraceSnapshotsDictionaryArchiveFile:(id)arg1;
- (id)init;

@end

