//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class MSPDroppedPin;

@protocol NMMapsAppXPCInterface
- (void)updateDroppedPin:(MSPDroppedPin *)arg1;
- (void)stopDirectionsWithCompletionHandler:(void (^)(void))arg1;
- (void)updateDirectionsStatusWithCompletionHandler:(void (^)(void))arg1;
- (void)clearPreviewRouteWithCompletionHandler:(void (^)(void))arg1;
- (void)selectPreviewRouteAtIndex:(unsigned long long)arg1 completionHandler:(void (^)(void))arg2;
@end

