//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (MapsStringDrawing)
- (void)_maps_drawInRect:(struct CGRect)arg1 withFont:(id)arg2;
- (void)_maps_drawAtPoint:(struct CGPoint)arg1 withFont:(id)arg2;
- (struct CGSize)_maps_sizeWithFont:(id)arg1 constrainedToSize:(struct CGSize)arg2 options:(long long)arg3;
- (struct CGSize)_maps_sizeWithFont:(id)arg1 constrainedToSize:(struct CGSize)arg2;
- (struct CGSize)_maps_sizeWithFont:(id)arg1;
@end

