//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (MapsExtra)
+ (id)distanceStringFromLocation:(id)arg1 toMapItem:(id)arg2 displaysDistanceAsSnippetLocationAboveThreshold:(_Bool)arg3 showsDistance:(out _Bool *)arg4;
+ (id)stringWithRemainingTime:(double)arg1 allowShortForm:(_Bool)arg2;
+ (id)stringWithRemainingTime:(double)arg1 allowShortForm:(_Bool)arg2 showPastTimes:(_Bool)arg3;
+ (id)_maps_formattedStringForInt:(long long)arg1;
- (_Bool)_maps_isOnlyWhiteSpaces;
- (_Bool)_maps_endsInAbbreviationPunctuation;
- (struct _NSRange)_maps_rangeForTimePartOfFormattedShortTimeString;
- (long long)fileCreationDateDescendingSort:(id)arg1;
@end

