//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsAction.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface OpenCommuteEntryAction : MapsAction
{
    NSString *_entryID;
}

@property(copy, nonatomic) NSString *entryID; // @synthesize entryID=_entryID;
- (void).cxx_destruct;
- (id)initWithEntry:(id)arg1;

@end

