//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIEvent, UIView;

@protocol PassThroughViewDelegate <NSObject>
- (UIView *)passThroughView;

@optional
- (_Bool)shouldPassPoint:(struct CGPoint)arg1 withEvent:(UIEvent *)arg2 inView:(UIView *)arg3;
@end

