//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol PassThroughViewDelegate;

__attribute__((visibility("hidden")))
@interface PassThroughView : UIView
{
    UIView *_targetView;
    id <PassThroughViewDelegate> _delegate;
}

@property(nonatomic) __weak id <PassThroughViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIView *targetView; // @synthesize targetView=_targetView;
- (void).cxx_destruct;
- (_Bool)_isTransparentFocusRegion;
- (id)_resolvedPassThroughView;
- (id)_unconditionallyPassthroughPoint:(struct CGPoint)arg1 withEvent:(id)arg2 toView:(id)arg3;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

