//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class GEOComposedRoute, RAPDisplayedRouteState;
@protocol RAPDisplayedDirectionsPlan;

@protocol RAPDirectionsDataSource
@property(readonly, nonatomic) _Bool isShowingDirections;
@property(readonly, nonatomic) id <RAPDisplayedDirectionsPlan> displayedDirectionsPlan;
@property(readonly, nonatomic) RAPDisplayedRouteState *currentDirections;
@property(readonly, nonatomic) GEOComposedRoute *activeComposedRoute;
@end

