//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DirectionsStepsTableViewController.h"

@protocol RAPDirectionsStepsTableViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface RAPDirectionsStepsTableViewController : DirectionsStepsTableViewController
{
    double _dummyTrailingViewWidth;
    id <RAPDirectionsStepsTableViewControllerDelegate> _instructionDelegate;
}

@property(nonatomic) __weak id <RAPDirectionsStepsTableViewControllerDelegate> instructionDelegate; // @synthesize instructionDelegate=_instructionDelegate;
- (void).cxx_destruct;
- (id)preferredMapsTheme;
- (double)_trailingViewWidth;
- (id)_rapDisclosureViewForCell:(id)arg1 routeStep:(id)arg2;
- (id)trailingViewForInstructionIncorrectView:(id)arg1;
- (void)_attachDisclosureViewToCell:(id)arg1 routeStep:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)init;

@end

