//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RAPCommentQuestion.h"

@class GEOComposedRouteStep, NSData, TransitDirectionsListItem;

__attribute__((visibility("hidden")))
@interface RAPInstructionCorrectionQuestion : RAPCommentQuestion
{
    NSData *_cellScreenshotImageData;
    GEOComposedRouteStep *_composedRouteStep;
    TransitDirectionsListItem *_listItem;
}

@property(readonly, nonatomic) TransitDirectionsListItem *listItem; // @synthesize listItem=_listItem;
@property(readonly, nonatomic) GEOComposedRouteStep *composedRouteStep; // @synthesize composedRouteStep=_composedRouteStep;
@property(copy, nonatomic) NSData *cellScreenshotImageData; // @synthesize cellScreenshotImageData=_cellScreenshotImageData;
- (void).cxx_destruct;
- (id)initWithReport:(id)arg1 parentQuestion:(id)arg2 composedRouteStep:(id)arg3 listItem:(id)arg4;
- (id)_commentsPlaceholderText;
- (void)fillIndexesForResponse:(id)arg1 problemAticRouteIndex:(id)arg2 correction:(id)arg3;
- (void)_fillSubmittableProblem:(id)arg1;

@end

