//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CLLocation, NSDate, UIImage;

__attribute__((visibility("hidden")))
@interface RAPPhoto : NSObject
{
    UIImage *_photo;
    NSDate *_date;
    CLLocation *_location;
}

@property(readonly, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(readonly, nonatomic) NSDate *date; // @synthesize date=_date;
@property(readonly, nonatomic) UIImage *photo; // @synthesize photo=_photo;
- (void).cxx_destruct;
- (id)initWithPhoto:(id)arg1 date:(id)arg2 location:(id)arg3;

@end

