//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RAPTablePartSection.h"

@class MKMapSnapshotOptions;

__attribute__((visibility("hidden")))
@interface RAPReportComposerLocationPartSection : RAPTablePartSection
{
    double _mapHeight;
    MKMapSnapshotOptions *_snapshotOptions;
    _Bool _showPin;
}

- (void).cxx_destruct;
- (id)cellForRowAtIndex:(long long)arg1;
- (void)registerReuseIdentifiersForCells;
- (long long)rowsCount;
- (id)initWithSnapshotOptions:(id)arg1 mapHeight:(double)arg2 showPin:(_Bool)arg3;
- (id)initWithMapType:(unsigned long long)arg1 mapRect:(CDStruct_02837cd9)arg2 showPin:(_Bool)arg3;

@end

