//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RAPTableCheckmarkRadioSection.h"

@class NSArray, NSString, RAPCollapsableHeaderFooterView;

__attribute__((visibility("hidden")))
@interface RAPTableCollapsableCheckmarkSection : RAPTableCheckmarkRadioSection
{
    RAPCollapsableHeaderFooterView *_collapsableHeaderView;
    long long _selectedIndex;
    NSString *_headerTitle;
    NSArray *_originalValues;
}

@property(readonly, nonatomic) NSArray *originalValues; // @synthesize originalValues=_originalValues;
- (id)headerTitle;
- (void).cxx_destruct;
- (void)didChange;
- (void)toggleCollapse;
- (void)selectedValueDidChange;
- (void)didSelectCellForRowAtIndex:(long long)arg1 tableIndexPath:(id)arg2;
- (void)_showAll;
- (Class)defaultCellClass;
- (void)setValues:(id)arg1;
- (void)setHeaderTitle:(id)arg1;
- (id)init;

@end

