//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ReservationTableViewCell.h"

@class NSString, UIStepper;

__attribute__((visibility("hidden")))
@interface ReservationRefinementPartySizeTableViewCell : ReservationTableViewCell
{
    UIStepper *_stepperControl;
    NSString *_valueTitleFormat;
}

@property(retain, nonatomic) NSString *valueTitleFormat; // @synthesize valueTitleFormat=_valueTitleFormat;
@property(readonly, nonatomic) UIStepper *stepperControl; // @synthesize stepperControl=_stepperControl;
- (void).cxx_destruct;
- (void)updateStepperValueToValue:(unsigned long long)arg1;
- (void)updateLabel;
- (void)valueChanged:(id)arg1;
- (void)setupConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

