//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GEOMapServiceTraits, GEORetainedSearchMetadata, GEOSearchCategory, NSString, PersonalizedItemManager, RAPAutoCompleteSearchManager, UserLocationSearchResult;

@protocol SearchDataProviding <NSObject>
@property(retain, nonatomic) PersonalizedItemManager *mapPersonalizedItems;
@property(retain, nonatomic) RAPAutoCompleteSearchManager *autoCompleteSearchRAPManager;
@property(retain, nonatomic) GEORetainedSearchMetadata *retainedSearchMetadata;
@property(retain, nonatomic) UserLocationSearchResult *userLocationSearchResult;
@property(retain, nonatomic) GEOSearchCategory *inputCategory;
@property(nonatomic) int searchMode;
- (void)setSearchCompletionFilterType:(long long)arg1;
- (void)clearAutocompleteResults;
- (_Bool)hasResults;
- (void)reset;
- (void)setInputText:(NSString *)arg1 traits:(GEOMapServiceTraits *)arg2 source:(int)arg3;
@end

