//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class AutocompleteContext, NSArray, NSString;
@protocol SearchAddressBookOperationDelegate;

__attribute__((visibility("hidden")))
@interface SearchAddressBookOperation : NSOperation
{
    NSString *_searchQuery;
    AutocompleteContext *_context;
    NSArray *_searchTerms;
    id <SearchAddressBookOperationDelegate> delegate;
}

@property(nonatomic) __weak id <SearchAddressBookOperationDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)main;
- (id)initWithSearchQuery:(id)arg1 context:(id)arg2;

@end

