//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface ShareItem : NSObject
{
}

+ (id)shareItemWithRoute:(id)arg1 startPOIShape:(id)arg2 endPOIShape:(id)arg3 includeRoutingApps:(_Bool)arg4;
+ (id)shareItemForCurrentLocationIncludingPrintActivity:(_Bool)arg1;
+ (id)shareItemWithSearchResult:(id)arg1 contact:(id)arg2 includePrintActivity:(_Bool)arg3;

@end

