//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SearchResultsHistoryRecorder.h"

#import "SearchHistoryRecorder-Protocol.h"

@class SearchResult;

__attribute__((visibility("hidden")))
@interface SingleResultSearchHistoryRecorder : SearchResultsHistoryRecorder <SearchHistoryRecorder>
{
    SearchResult *_searchResult;
}

@property(retain, nonatomic) SearchResult *searchResult; // @synthesize searchResult=_searchResult;
- (void).cxx_destruct;
- (void)recordItemInHistory;
- (id)initWithTicket:(id)arg1 searchResults:(id)arg2 auxiliaryControlsOrigin:(long long)arg3 hasRefinedMapItems:(_Bool)arg4 tracksRAPReportingOnly:(_Bool)arg5;
- (id)initWithTicket:(id)arg1 searchResult:(id)arg2 auxiliaryControlsOrigin:(long long)arg3 hasRefinedMapItems:(_Bool)arg4 tracksRAPReportingOnly:(_Bool)arg5;

@end

