//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, UIColor;

@protocol TransitDirectionsListExpandableItem <NSObject>
@property(copy, nonatomic) NSArray *expandedItems;
@property(nonatomic) _Bool expanded;
- (UIColor *)secondaryInstructionColor;
- (unsigned long long)numberOfSubItemsWithForceExpand:(_Bool)arg1;
- (_Bool)shouldEnableExpandedButton;
- (NSString *)expandingButtonTitleForExpandedState:(_Bool)arg1;
@end

