//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TransitDirectionsIconCell.h"

@class NSLayoutConstraint, NSMutableArray, NSNumber, UIFont, _MKUILabel;

__attribute__((visibility("hidden")))
@interface TransitDirectionsPassItemCell : TransitDirectionsIconCell
{
    NSLayoutConstraint *_topToPrimaryLabelBaselineConstraint;
    NSLayoutConstraint *_bottomToPrimaryLabelBaselineConstraint;
    NSNumber *_overriddenTopToBaselineDistance;
    NSNumber *_overriddenBaselineToBottomDistance;
    NSMutableArray *_cellSpecificConstraints;
    UIFont *_primaryLabelFont;
    _Bool _adjustUIForRAP;
    _MKUILabel *_primaryLabel;
    _MKUILabel *_secondaryLabel;
}

@property(readonly, nonatomic) _MKUILabel *secondaryLabel; // @synthesize secondaryLabel=_secondaryLabel;
@property(readonly, nonatomic) _MKUILabel *primaryLabel; // @synthesize primaryLabel=_primaryLabel;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)setNavigationState:(long long)arg1;
- (void)_updateLineSpacing;
- (void)_updateFonts;
- (double)_topToFirstBaselineDistance;
- (double)_primaryLabelLineSpacing;
- (void)configureWithItem:(id)arg1;
- (id)cellSpecificConstraints;
- (id)_initialConstraints;
- (void)_createSubviews;
- (void)_contentSizeCategoryDidChange;
@property(copy, nonatomic) NSNumber *overriddenBaselineToBottomDistance;
@property(copy, nonatomic) NSNumber *overriddenTopToBaselineDistance;
@property(nonatomic) _Bool adjustUIForRAP;

@end

