//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TwoPartTopBarLabel.h"

__attribute__((visibility("hidden")))
@interface TwoPartTimeLabel : TwoPartTopBarLabel
{
    unsigned long long _remainingMinutes;
}

@property(nonatomic) unsigned long long remainingMinutes; // @synthesize remainingMinutes=_remainingMinutes;
- (void)updateContent;
- (id)initWithFrame:(struct CGRect)arg1;

@end

