//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (TransitDirectionsListArtwork)
+ (double)_maps_minSideLengthForShieldSize:(long long)arg1;
+ (id)_maps_maneuverImageForTransitArrivalInfo:(id)arg1 shieldSize:(long long)arg2 forDarkBackground:(_Bool)arg3;
+ (id)interSystemTransferFromHexColor:(id)arg1 toHexColor:(id)arg2 ImageWithSize:(long long)arg3 scale:(double)arg4;
@end

