//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (HIKitExtras)
+ (double)labelSpacingDerivedFromHIBaselineOffset:(double)arg1 fromFont:(id)arg2;
+ (double)labelSpacingDerivedFromHIBaselineOffset:(double)arg1 fromBottomLineBaselineOfFont:(id)arg2 toTopLineBaselineOfFont:(id)arg3;
@end

