//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPopoverPresentationController.h>

@interface UIPopoverPresentationController (UIKitExtras)
- (void)_maps_hideArrowWithOffset:(double)arg1;
- (void)_maps_setSource:(id)arg1;
@end

