//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (MapsSizeClassShim)
- (CDStruct_912cb5d2)_maps_sizeClassPair;
- (long long)_maps_sizeClassForAxis:(long long)arg1;
@end

