//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GEOComposedWaypoint, NSError, WaypointsLoader;
@protocol GEOMapServiceTicket;

@protocol WaypointsLoaderDelegate <NSObject>
- (void)waypointsLoader:(WaypointsLoader *)arg1 didFailWithError:(NSError *)arg2;
- (void)waypointsLoader:(WaypointsLoader *)arg1 didLoadWaypointsForStart:(GEOComposedWaypoint *)arg2 startTicket:(id <GEOMapServiceTicket>)arg3 end:(GEOComposedWaypoint *)arg4 endTicket:(id <GEOMapServiceTicket>)arg5;
@end

