/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:00 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACM2SVHTTPHandler.h>

@interface ACM2SVHTTPGetTrustedDevicesHandler : ACM2SVHTTPHandler
-(id)convertErrorToACMError:(id)arg1 ;
-(id)initWithContext:(id)arg1 ;
@end

