/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:01 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMAppleConnectImplComponents.h>

@interface ACMExternalAppleConnectImplComponents : ACMAppleConnectImplComponents
+(id)components;
-(id)createHandlerWithClass:(Class)arg1 context:(id)arg2 ;
-(id)twoSVController;
-(id)uiController;
-(id)createAppleConnectImpl;
-(id)createAppleConnectImplWithMasterObject:(id)arg1 ;
-(BOOL)uiControllerLoaded;
-(void)unloadUIController;
-(id)createAuthenticationRequest;
-(id)preferences;
@end

