/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:00 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACMSignInDialogDelegate <NSObject>
@required
-(void)onIForgot:(id)arg1;
-(void)onSignIn:(id)arg1;
-(void)onSignInCancel:(id)arg1;
-(void)signInDialogWillBecomeEnabled;
-(void)signInDialogDidBecomeEnabled;
-(void)signInDialogWillBecomeDisabled;
-(void)signInDialogDidBecomeDisabled;

@end

