/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:01 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class UIImage, UIColor, NSString;


@protocol ACMSignInDialogSimpleProtocol <ACMSignInDialogProtocol>
@property (nonatomic,retain) UIImage * logo; 
@property (nonatomic,retain) UIColor * backgroundColor; 
@property (nonatomic,retain) NSString * accountNameFieldPlaceholder; 
@required
-(void)setLogo:(id)arg1;
-(UIImage *)logo;
-(void)setAccountNameFieldPlaceholder:(id)arg1;
-(NSString *)accountNameFieldPlaceholder;
-(void)setBackgroundColor:(id)arg1;
-(UIColor *)backgroundColor;

@end

