//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UILabel, UITextView, UIView;

@interface VOTUICaptionPanelViewController : UIViewController
{
    UIView *_backgroundView;
    UILabel *_captionPanelLanguage;
    UITextView *_captionPanelText;
    double _captionPanelHeight;
}

@property(nonatomic) double captionPanelHeight; // @synthesize captionPanelHeight=_captionPanelHeight;
@property(retain, nonatomic) UITextView *captionPanelText; // @synthesize captionPanelText=_captionPanelText;
@property(retain, nonatomic) UILabel *captionPanelLanguage; // @synthesize captionPanelLanguage=_captionPanelLanguage;
- (void).cxx_destruct;
- (void)parseMessage:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_layoutSubviews;

@end

