/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 5:03:45 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libAppleSSEExt.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface BAASupport : NSObject
+(void)setBlessedUser:(unsigned)arg1 keybagUUID:(unsigned char)arg2 ;
+(int)getCertificateExpirationDate:(double*)arg1 ;
+(int)issueNewCertificate;
+(void)initialize;
+(void)setDelegate:(id)arg1 ;
+(int)prepare;
@end

