/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:19:20 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_dispatch_object.h>
#import <libobjc.A.dylib/OS_dispatch_queue_attr.h>

@protocol OS_dispatch_queue_attr <OS_dispatch_object>
@end


@class NSString;

@interface OS_dispatch_queue_attr : OS_dispatch_object <OS_dispatch_queue_attr>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)load;
-(id)init;
@end

