/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:19:20 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_object.h>

@interface OS_voucher : OS_object
+(void)load;
-(void)_xref_dispose;
-(void)_dispose;
-(id)init;
-(oneway void)release;
-(id)retain;
-(id)debugDescription;
@end

