//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SafariServices/_SFActivity.h>

@class TabDocument;

@interface Activity : _SFActivity
{
    TabDocument *_tabDocument;
}

@property(readonly, nonatomic) TabDocument *tabDocument; // @synthesize tabDocument=_tabDocument;
- (void).cxx_destruct;
- (id)init;
- (id)initWithTabDocument:(id)arg1;

@end

