//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SafariServices/_SFBrowserSavedState.h>

@class NSString;

@interface PPTTestBrowserSavedState : _SFBrowserSavedState
{
    unsigned long long _tabsCount;
    NSString *_initalURLString;
}

@property(copy, nonatomic) NSString *initalURLString; // @synthesize initalURLString=_initalURLString;
@property(nonatomic) unsigned long long tabsCount; // @synthesize tabsCount=_tabsCount;
- (void).cxx_destruct;
- (_Bool)activeDocumentIsValidForBrowserControllerWithUUID:(id)arg1;
- (id)savedTabsStateForBrowserControllerWithUUID:(id)arg1 initialURLString:(id)arg2;
- (id)savedTabsStateForBrowserControllerWithUUID:(id)arg1;

@end

