//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, TabOverview, TabOverviewItemLayoutInfo, UIImage;

@interface TabOverviewItem : NSObject
{
    _Bool _hidden;
    _Bool _recording;
    _Bool _usesDarkTheme;
    _Bool _closing;
    NSString *_title;
    UIImage *_icon;
    TabOverviewItemLayoutInfo *_layoutInfo;
    TabOverview *_tabOverview;
}

@property(nonatomic) __weak TabOverview *tabOverview; // @synthesize tabOverview=_tabOverview;
@property(retain, nonatomic) TabOverviewItemLayoutInfo *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(nonatomic) _Bool closing; // @synthesize closing=_closing;
@property(nonatomic) _Bool usesDarkTheme; // @synthesize usesDarkTheme=_usesDarkTheme;
@property(nonatomic, getter=isRecording) _Bool recording; // @synthesize recording=_recording;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
- (void).cxx_destruct;

@end

