//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class UIColor;

@interface VibrantLabelView : UILabel
{
    UIColor *_nonVibrantTextColor;
    _Bool _usesVibrantAppearance;
}

@property(retain, nonatomic) UIColor *nonVibrantTextColor; // @synthesize nonVibrantTextColor=_nonVibrantTextColor;
@property(nonatomic) _Bool usesVibrantAppearance; // @synthesize usesVibrantAppearance=_usesVibrantAppearance;
- (void).cxx_destruct;
- (void)_updateVibrancy;
- (void)setTextColor:(id)arg1;
- (void)_reduceTransparencyStatusDidChange:(id)arg1;

@end

