//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__MailboxContentViewControllerAccessibility_super.h"

@interface MailboxContentViewControllerAccessibility : __MailboxContentViewControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_updateBackButtonImageWithCount:(unsigned long long)arg1;
- (_Bool)_accessibilityIsDraftsMailbox;
- (_Bool)_accessibilityIsOutbox;
- (id)_accessibilityMallSources;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)setTableView:(id)arg1;
- (void)_accessibilityLoadAccessibilityInformation;

@end

