//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__PKPassHeaderViewAccessibility_super.h"

@interface PKPassHeaderViewAccessibility : __PKPassHeaderViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)accessibilityElements;
- (id)_accessibilityValueAggregateElement;
- (id)_accessibilityTitleAggregateElement;
- (void)_accessibilitySetStoredValueAggregate:(id)arg1;
- (id)_accessibilityStoredValueAggregate;
- (void)_accessibilitySetStoredTitleAggregate:(id)arg1;
- (id)_accessibilityStoredTitleAggregate;

@end

