//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__TVRTouchpadViewAccessibility_super.h"

@interface TVRTouchpadViewAccessibility : __TVRTouchpadViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_accessibilitySetIsDirectTouching:(_Bool)arg1;
- (_Bool)_accessibilityIsDirectTouching;
- (void)_accessibilityFocusChanged:(id)arg1;
- (id)_accessibilityPathInTouchpadViewForShape:(long long)arg1;
- (struct CGRect)_accessibilityFrameInTouchpadViewForShape:(long long)arg1;
- (double)_accessibilityPositionForShape:(long long)arg1 xAxis:(_Bool)arg2;
- (id)_accessibilitySwitchControlElements;
- (void)_accessibilityPerformTouchpadAction:(long long)arg1;
- (long long)accessibilityNavigationStyle;
- (id)accessibilityElements;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (_Bool)accessibilityActivate;
- (_Bool)_accessibilitySupportsActivateAction;
- (_Bool)isAccessibilityElement;

@end

