//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UITraitEnvironment-Protocol.h"

@class UITraitCollection;

@protocol FutureTraitEnvironment <UITraitEnvironment>
@property(retain, nonatomic) UITraitCollection *futureTraitCollection;

@optional
@property(readonly, nonatomic) _Bool isTransitioningTraitCollection;
@end

