//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@class UILabel;
@protocol InboxTableViewDelegate;

@interface InboxTableView : UITableView
{
    UILabel *_noContentView;
    id <InboxTableViewDelegate> _listViewDelegate;
}

@property(nonatomic) __weak id <InboxTableViewDelegate> listViewDelegate; // @synthesize listViewDelegate=_listViewDelegate;
- (void).cxx_destruct;
- (void)setShowNoContentString:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;

@end

