//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CarDarkening-Protocol.h"

@class NSDictionary;
@protocol CarCardContentDelegate;

@protocol CarCardContent <CarDarkening>
@property(readonly, nonatomic) _Bool hasContent;
@property(nonatomic) __weak id <CarCardContentDelegate> cardContentDelegate;
- (void)updateLayout;

@optional
@property(retain, nonatomic) NSDictionary *dynamicDimensionGuides;
@end

