//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView, UIViewController;

@protocol CarCard <NSObject>
@property(copy, nonatomic) CDUnknownBlockType selectionHandler;
@property(nonatomic, getter=isTransitioning) _Bool transitioning;
@property(nonatomic) unsigned long long nightModeBehavior;
@property(retain, nonatomic) UIView *accessoryView;
@property(nonatomic) unsigned long long accessory;
@property(nonatomic) CDStruct_87f3a021 layout;
@property(retain, nonatomic) UIViewController *content;
@end

