//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIImage;

@protocol CarCardStyleProviding <NSObject>
- (UIImage *)maskImageForCarCardLayout:(CDStruct_87f3a021)arg1 scale:(double)arg2;
- (UIImage *)backgroundImageForCarCardLayout:(CDStruct_87f3a021)arg1 controlState:(unsigned long long)arg2 scale:(double)arg3 nightMode:(_Bool)arg4;

@optional
@property(nonatomic, getter=isTransitioning) _Bool transitioning;
- (CDStruct_87f3a021)validateCarCardLayout:(CDStruct_87f3a021)arg1;
@end

