//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "NavSignLabelDelegate-Protocol.h"
#import "NavSignManeuverGuidanceInfoObserver-Protocol.h"

@class CarManeuverViewStyle, GuidanceManeuverView, NSArray, NSDictionary, NSMutableDictionary, NSString, NSUUID, NavSignLabel, NavSignLaneGuidanceInfo, NavSignLaneGuidanceView, NavSignManeuverGuidanceInfo, UIImage, UIImageView;
@protocol CarManeuverViewAnalyticsDelegate;

__attribute__((visibility("hidden")))
@interface CarManeuverView : UIView <NavSignManeuverGuidanceInfoObserver, NavSignLabelDelegate>
{
    NavSignLaneGuidanceView *_laneGuidanceView;
    GuidanceManeuverView *_maneuverView;
    NavSignLabel *_distanceLabel;
    NavSignLabel *_instructionsLabel;
    UIImageView *_shieldView;
    UIImage *_shieldImage;
    NSUUID *_lastRenderedShieldSignID;
    unsigned long long _maxNumberOfVisibleLanes;
    _Bool _secondarySignVisible;
    long long _displayedLightLevel;
    NavSignManeuverGuidanceInfo *_guidance;
    NavSignLaneGuidanceInfo *_laneGuidance;
    unsigned long long _compressionStage;
    id <CarManeuverViewAnalyticsDelegate> _analyticsDelegate;
    NSDictionary *_sizeByCompressionStage;
    CarManeuverViewStyle *_configuredStyle;
    CarManeuverViewStyle *_lowGuidanceStyle;
    NSMutableDictionary *_dynamicConstraints;
    NSArray *_myConstraints;
    long long _labelLineBreakMode;
    struct CGSize _desiredSize;
    struct CGSize _actualSize;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(nonatomic) long long labelLineBreakMode; // @synthesize labelLineBreakMode=_labelLineBreakMode;
@property(retain, nonatomic) NSArray *myConstraints; // @synthesize myConstraints=_myConstraints;
@property(retain, nonatomic) NSMutableDictionary *dynamicConstraints; // @synthesize dynamicConstraints=_dynamicConstraints;
@property(readonly, nonatomic) CarManeuverViewStyle *lowGuidanceStyle; // @synthesize lowGuidanceStyle=_lowGuidanceStyle;
@property(readonly, nonatomic) CarManeuverViewStyle *configuredStyle; // @synthesize configuredStyle=_configuredStyle;
@property(readonly, nonatomic) struct CGSize actualSize; // @synthesize actualSize=_actualSize;
@property(retain, nonatomic) NSDictionary *sizeByCompressionStage; // @synthesize sizeByCompressionStage=_sizeByCompressionStage;
@property(nonatomic) struct CGSize desiredSize; // @synthesize desiredSize=_desiredSize;
@property(nonatomic) __weak id <CarManeuverViewAnalyticsDelegate> analyticsDelegate; // @synthesize analyticsDelegate=_analyticsDelegate;
@property(nonatomic) unsigned long long compressionStage; // @synthesize compressionStage=_compressionStage;
@property(nonatomic) _Bool secondarySignVisible; // @synthesize secondarySignVisible=_secondarySignVisible;
@property(readonly, nonatomic) NavSignLaneGuidanceInfo *laneGuidance; // @synthesize laneGuidance=_laneGuidance;
@property(readonly, nonatomic) NavSignManeuverGuidanceInfo *guidance; // @synthesize guidance=_guidance;
@property(nonatomic) long long displayedLightLevel; // @synthesize displayedLightLevel=_displayedLightLevel;
- (void).cxx_destruct;
- (void)navSignLabel:(id)arg1 didSelectAlternate:(unsigned long long)arg2;
- (void)maneuverGuidanceInfoDidChange:(id)arg1;
- (_Bool)_shouldShowLaneGuidance;
@property(readonly) _Bool shouldShowLaneGuidance;
- (void)showLaneGuidanceFromManeuver:(id)arg1;
- (void)hideLaneGuidance;
- (void)updateLaneGuidance:(id)arg1;
- (void)showLaneGuidance:(id)arg1;
- (id)_shieldImage;
- (void)_updateShield;
- (void)_updateConstraints;
- (void)_updateStyling;
- (void)_updateSubviews;
- (void)_updateContents;
- (void)_updateLabels;
- (void)_setupConstraints;
- (void)_setupStyling;
- (void)_setupSubviews;
- (void)_resetSizeByCompressionStageIfNeeded;
- (struct CGSize)sizeForCompressionStage:(unsigned long long)arg1;
@property(readonly, nonatomic) int variant;
@property(readonly, nonatomic) CarManeuverViewStyle *style;
- (void)layoutSubviews;
- (void)invalidateIntrinsicContentSize;
- (struct CGSize)intrinsicContentSize;
- (id)initWithGuidance:(id)arg1 variant:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

