//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSOperationQueue, _MKQuickRouteManager;

__attribute__((visibility("hidden")))
@interface CarQuickRouteRefreshOperation : NSOperation
{
    _MKQuickRouteManager *_quickRouteManager;
    NSOperationQueue *_operationQueue;
}

+ (_Bool)isFullThrottleEngaged;
+ (void)engageFullThrottleForInterval:(double)arg1;
+ (void)suspendQueues:(_Bool)arg1;
+ (id)throttleStateDescription;
+ (unsigned long long)throttlePreventionLevel;
+ (void)initialize;
@property(nonatomic) __weak NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) _MKQuickRouteManager *quickRouteManager; // @synthesize quickRouteManager=_quickRouteManager;
- (void).cxx_destruct;
- (void)main;
- (id)initWithQuickRoute:(id)arg1;
- (id)description;

@end

