//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PassThroughViewController.h"

@protocol UIFocusItem;

__attribute__((visibility("hidden")))
@interface CarRoutePlanningViewController : PassThroughViewController
{
    id <UIFocusItem> _initialFocusItem;
}

@property(nonatomic) __weak id <UIFocusItem> initialFocusItem; // @synthesize initialFocusItem=_initialFocusItem;
- (void).cxx_destruct;
- (void)viewDidAppear:(_Bool)arg1;

@end

