//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CarGuidanceCard-Protocol.h"

@class NSArray, NSString, UILabel;
@protocol CarGuidanceCardDelegate;

__attribute__((visibility("hidden")))
@interface CarToggledGuidanceSign : UIView <CarGuidanceCard>
{
    UILabel *_label;
    NSArray *_labelStringsForNavigationType;
    id <CarGuidanceCardDelegate> _guidanceCardDelegate;
    unsigned long long _navigationType;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(nonatomic) unsigned long long navigationType; // @synthesize navigationType=_navigationType;
@property(nonatomic) __weak id <CarGuidanceCardDelegate> guidanceCardDelegate; // @synthesize guidanceCardDelegate=_guidanceCardDelegate;
- (void).cxx_destruct;
- (void)updateWithGroupAnimation:(id)arg1;
@property(readonly, nonatomic) _Bool hasContent;
- (void)_updateText;
- (void)_updateStyling;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

