//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ClientTypeResolverSource.h"

@class AddressBookManager, CoreRoutineLocationOfInterestManager;

__attribute__((visibility("hidden")))
@interface ClientTypeResolverPersonalizedItemSource : ClientTypeResolverSource
{
    AddressBookManager *_addressBookManager;
    CoreRoutineLocationOfInterestManager *_locationOfInterestManager;
}

@property(retain, nonatomic) CoreRoutineLocationOfInterestManager *locationOfInterestManager; // @synthesize locationOfInterestManager=_locationOfInterestManager;
@property(retain, nonatomic) AddressBookManager *addressBookManager; // @synthesize addressBookManager=_addressBookManager;
- (void).cxx_destruct;
- (void)addressOrLOIWithType:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (id)cachedLOIWithType:(int)arg1;
- (id)cachedAddressWithType:(int)arg1;
- (id)cachedObjectWithType:(int)arg1;
- (void)objectWithType:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)hasObjectWithType:(int)arg1;
- (id)knownTypes;
- (_Bool)homeAndWorkEnabled;
- (id)initWithAddressBookManager:(id)arg1 locationOfInterestManager:(id)arg2;

@end

