//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsAction.h"

__attribute__((visibility("hidden")))
@interface DisplayModeNavAction : MapsAction
{
    _Bool _showDetails;
}

@property(nonatomic) _Bool showDetails; // @synthesize showDetails=_showDetails;
- (_Bool)isCompatibleWithNavigation;
- (id)initWithShowDetails:(_Bool)arg1;

@end

