//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/MKViewWithHairline.h>

@class NSString, UIButton;

__attribute__((visibility("hidden")))
@interface ExtensionsActionView : MKViewWithHairline
{
    UIButton *_button;
    CDUnknownBlockType _didTapButton;
}

@property(copy, nonatomic) CDUnknownBlockType didTapButton; // @synthesize didTapButton=_didTapButton;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *buttonTitle;
- (void)_didTap;
- (struct CGSize)intrinsicContentSize;
- (void)_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

