//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GeoServices/GEOTransitOptions.h>

@interface GEOTransitOptions (Preferences)
+ (int)sortOptionFromDefaults;
- (void)_populateGeoAvoidedTransitModeForTransitMode:(long long)arg1;
- (void)populateAvoidedModeFromModes:(long long)arg1;
- (long long)_individualModeForGEOAvoidedMode:(int)arg1;
@property(readonly, nonatomic) long long mapsTransitModes;
@end

