//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PersonalizedItemSource.h"

@class NSArray, NSMutableSet, NSObject, NSTimer, RTRoutineManager;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface HomeWorkRoutineItemSource : PersonalizedItemSource
{
    NSArray *_items;
    NSObject<OS_dispatch_queue> *_lock;
    NSTimer *_coalesceTimer;
    RTRoutineManager *_routineManager;
    _Bool _routineEnabled;
    NSMutableSet *_currentlyProcessingLoiItems;
}

- (void).cxx_destruct;
- (void)personalizedItemDidChange:(id)arg1;
- (void)fetchHomeWorkRoutineLocations;
- (_Bool)shouldUpdateCoreRoutineWithMapsSyncData;
- (void)checkRoutineAndFetchLOIS;
- (void)setNeedsUpdateWithCoalescing;
- (void)updateItemsIfNeeded:(id)arg1;
- (void)_geocodeAddress:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)allItems;
- (id)init;

@end

