//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsAppTestRoute.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface MapsAppTestGuidance : MapsAppTestRoute
{
    NSTimer *_guidanceTimer;
    long long _swipeCount;
}

@property(readonly, nonatomic) long long swipeCount; // @synthesize swipeCount=_swipeCount;
- (void).cxx_destruct;
- (_Bool)_testIsStepping;
- (void)_runPlayWithTraySubtest;
- (void)_endGuidanceNavOrSteppingMode;
- (void)doAfterSubTestForShowingSign;
- (void)_steppingSignDidChange;
- (void)_gotoNextStep;
- (void)willUpdateNavigationSign;
- (void)_guidanceOrSteppingDidShowFirstSign;
- (id)_subTestNameForGoingToGuidanceStep:(long long)arg1 forSwipeCount:(long long)arg2;
- (void)_enterGuidanceNavOrSteppingMode;
- (void)doAfterSubTestForDisplayingRoutes;
- (_Bool)runTest;
- (void)cleanup:(_Bool)arg1;
- (id)initWithApplication:(id)arg1 testName:(id)arg2 options:(id)arg3;

@end

