//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NavdDoomStorage;

@protocol NavdDoomConductorObserver <NSObject>

@optional
- (void)updatedSnapshot:(NavdDoomStorage *)arg1;
- (void)didEndUpdate;
- (void)didScheduleWakeup;
- (void)didFireAlert;
- (void)willFireAlert;
- (void)didUpdateRoutes;
- (void)willUpdateRoutes;
- (void)didUpdateDestinations;
- (void)willUpdateDestinations;
- (void)didUpdateWindow;
- (void)didInvalidateWindow;
- (void)didUpdateExitTime;
- (void)willUpdateExitTime;
- (void)willStartUpdate;
@end

