//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NavSignLayoutBase.h"

#import "NavManeuverSignLayoutDelegate-Protocol.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface NavManeverSignLayoutBase : NavSignLayoutBase <NavManeuverSignLayoutDelegate>
{
}

- (double)shieldViewTopMarginForSign:(id)arg1;
- (long long)maneuverViewPositionForSign:(id)arg1;
- (double)maneuverViewTopMarginForSign:(id)arg1;
- (struct CGSize)maneuverViewSizeForSign:(id)arg1;
- (CDStruct_092aca68)maneuverViewArrowMetricsForSign:(id)arg1;
- (_Bool)forceHideShieldViewForSign:(id)arg1;
- (_Bool)forceHideManeuverViewForSign:(id)arg1;
- (_Bool)shouldAlignMajorLabelToTrailingForSign:(id)arg1;
- (_Bool)shouldAlignMajorLabelToLeadingForSign:(id)arg1;
- (double)navSignView:(id)arg1 textTrailingMarginForMajorText:(_Bool)arg2;
- (_Bool)_shouldShowManeuverViewForSign:(id)arg1;
- (_Bool)_shouldShowExitShieldForSign:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

