//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSTimer.h>

@interface NSTimer (MapsSharedExtras)
+ (id)_maps_scheduledTimerWithFireDate:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)_maps_scheduledTimerWithTimeInterval:(double)arg1 repeats:(_Bool)arg2 block:(CDUnknownBlockType)arg3;
@end

