//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsAction.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface OpenTransitIncidentsAction : MapsAction
{
    NSArray *_incidents;
}

@property(copy, nonatomic) NSArray *incidents; // @synthesize incidents=_incidents;
- (void).cxx_destruct;
- (id)initWithIncidents:(id)arg1;

@end

