//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NavModeController.h"

@class PedestrianNavContainerViewController;

__attribute__((visibility("hidden")))
@interface PedestrianNavModeController : NavModeController
{
    _Bool _previousLocationViewEnabled;
    _Bool _playManeuverHaptics;
    long long _previousHeadingIndicatorStyle;
    PedestrianNavContainerViewController *_pedestrianContainerViewController;
    unsigned long long _lastStepIndexPlayedSoundFor;
}

@property(nonatomic) unsigned long long lastStepIndexPlayedSoundFor; // @synthesize lastStepIndexPlayedSoundFor=_lastStepIndexPlayedSoundFor;
@property(nonatomic) _Bool playManeuverHaptics; // @synthesize playManeuverHaptics=_playManeuverHaptics;
@property(retain, nonatomic) PedestrianNavContainerViewController *pedestrianContainerViewController; // @synthesize pedestrianContainerViewController=_pedestrianContainerViewController;
@property(nonatomic) long long previousHeadingIndicatorStyle; // @synthesize previousHeadingIndicatorStyle=_previousHeadingIndicatorStyle;
@property(nonatomic) _Bool previousLocationViewEnabled; // @synthesize previousLocationViewEnabled=_previousLocationViewEnabled;
- (void).cxx_destruct;
- (unsigned int)_soundForManeuverType:(int)arg1;
- (void)navigationServiceDidArrive:(id)arg1;
- (void)navigationService:(id)arg1 willAnnounce:(unsigned long long)arg2 inSeconds:(double)arg3;
- (void)prepareToRunNavigationAnimated:(_Bool)arg1;
- (void)resignCurrentModeAnimated:(_Bool)arg1 toMode:(id)arg2;
- (void)becomeCurrentModeWithViews:(id)arg1 animated:(_Bool)arg2 state:(id)arg3 fromMode:(id)arg4;
- (id)containerViewController;
- (id)viewController;
- (id)init;

@end

