//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsAction.h"

@class GEORPProblemStatusResponse, MKMapItem;

__attribute__((visibility("hidden")))
@interface PresentRAPAction : MapsAction
{
    GEORPProblemStatusResponse *_response;
    MKMapItem *_mapItem;
}

@property(retain, nonatomic) MKMapItem *mapItem; // @synthesize mapItem=_mapItem;
@property(retain, nonatomic) GEORPProblemStatusResponse *response; // @synthesize response=_response;
- (void).cxx_destruct;
- (id)initWithResponse:(id)arg1;
- (id)initWithMapItem:(id)arg1;

@end

