//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class RecentsDataProvider;

@protocol RecentsDataProviderDelegate <NSObject>
- (void)recentsDataProviderDidUpdate:(RecentsDataProvider *)arg1;

@optional
- (void)_recentsDataProviderDidLoadRecents:(RecentsDataProvider *)arg1;
- (void)_recentsDataProviderDidLoadSuggestions:(RecentsDataProvider *)arg1;
- (void)_recentsDataProviderDidEndLoadingSuggestions:(RecentsDataProvider *)arg1;
- (void)_recentsDataProviderWillBeginLoadingSuggestions:(RecentsDataProvider *)arg1;
@end

