//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIAlertController.h>

@class RideBookingRequestRideStatus;

__attribute__((visibility("hidden")))
@interface RidesharingPartySizeSelectionAlertController : UIAlertController
{
    CDUnknownBlockType _didFinishSelectingPartySize;
    RideBookingRequestRideStatus *_requestRideStatus;
}

+ (id)ridesharingPartySizeSelectionAlertControllerWithRequestRideStatus:(id)arg1;
@property(retain, nonatomic) RideBookingRequestRideStatus *requestRideStatus; // @synthesize requestRideStatus=_requestRideStatus;
@property(copy, nonatomic) CDUnknownBlockType didFinishSelectingPartySize; // @synthesize didFinishSelectingPartySize=_didFinishSelectingPartySize;
- (void).cxx_destruct;

@end

