//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface RouteTrafficCameraFeaturesUpdater : NSObject
{
}

- (id)_nearestTrafficCameraInCameras:(id)arg1 onRoute:(id)arg2 ofType:(long long)arg3 fromCoordinate:(CDStruct_f48a8b00)arg4 withLabelState:(long long)arg5;
- (void)updateTrafficCameras:(id)arg1 onRoute:(id)arg2 forLocation:(id)arg3;

@end

