//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OrderedDataSource;

__attribute__((visibility("hidden")))
@interface SearchResultsDataSourceContent : NSObject
{
    id <OrderedDataSource> _orderedDataSource;
}

@property(retain, nonatomic) id <OrderedDataSource> orderedDataSource; // @synthesize orderedDataSource=_orderedDataSource;
- (void).cxx_destruct;
- (id)objectAtIndexPath:(id)arg1;
- (long long)numberOfRowsInSection:(long long)arg1;
- (long long)numberOfSections;
- (unsigned long long)count;
- (id)objects;
- (id)initWithOrderedDataSource:(id)arg1;

@end

