//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CPDistributedMessagingCenter;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface ServiceBundleIPCInterface : NSObject
{
    CPDistributedMessagingCenter *_messagingCenter;
    NSObject<OS_dispatch_queue> *_messagingQueue;
}

+ (id)sharedInterface;
- (void).cxx_destruct;
- (void)mapsDidUpdateLockScreenState:(id)arg1;
- (void)mapsDidUpdateGuidanceState:(id)arg1;
- (id)init;

@end

