//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SettingsTableViewCell.h"

@class MapsThemeLabel, UISwitch;

__attribute__((visibility("hidden")))
@interface SettingsSwitchTableViewCell : SettingsTableViewCell
{
    MapsThemeLabel *_titleLabel;
    UISwitch *_switchControl;
}

@property(nonatomic) __weak UISwitch *switchControl; // @synthesize switchControl=_switchControl;
@property(nonatomic) __weak MapsThemeLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;

@end

