//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsLargerHitTargetButton.h"

@class NSLayoutConstraint, UIColor, UIView;

__attribute__((visibility("hidden")))
@interface TopBarAlertButton : MapsLargerHitTargetButton
{
    double _progress;
    UIView *_fillView;
    NSLayoutConstraint *_horizontalConstraint;
    _Bool _focusMode;
    UIColor *_primaryColor;
    UIColor *_secondaryColor;
    UIColor *_progressFillColor;
}

@property(retain, nonatomic) UIColor *progressFillColor; // @synthesize progressFillColor=_progressFillColor;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) UIColor *secondaryColor; // @synthesize secondaryColor=_secondaryColor;
@property(retain, nonatomic) UIColor *primaryColor; // @synthesize primaryColor=_primaryColor;
@property(nonatomic) _Bool focusMode; // @synthesize focusMode=_focusMode;
- (void).cxx_destruct;
- (void)_updateProgressConstraint;
- (void)setProgessFillColor:(id)arg1;
- (void)_insertFillViewIfNecessary;
- (void)didMoveToWindow;
- (void)_updateColorSettings;
- (void)_updateColors;
- (void)layoutSubviews;
- (_Bool)canBecomeFocused;

@end

