//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsThemeView.h"

@class MapsThemeLabel, NSString, UIImage, UIImageView;

__attribute__((visibility("hidden")))
@interface TrafficFeatureTitleView : MapsThemeView
{
    UIImageView *_imageView;
    MapsThemeLabel *_titleLabel;
    MapsThemeLabel *_subtitleLabel;
}

@property(readonly, nonatomic) MapsThemeLabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, nonatomic) MapsThemeLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
@property(copy, nonatomic) NSString *subtitle;
@property(copy, nonatomic) NSString *title;
@property(retain, nonatomic) UIImage *image;
- (id)initWithFrame:(struct CGRect)arg1;

@end

