//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

__attribute__((visibility("hidden")))
@interface TransitDirectionsListTableView : UITableView
{
    _Bool _performingBatchUpdate;
    CDUnknownBlockType _onBoundsChangeDuringBatchUpdate;
}

@property(copy, nonatomic) CDUnknownBlockType onBoundsChangeDuringBatchUpdate; // @synthesize onBoundsChangeDuringBatchUpdate=_onBoundsChangeDuringBatchUpdate;
- (void).cxx_destruct;
- (void)setBounds:(struct CGRect)arg1;
- (void)_performBatchUpdates:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;

@end

