//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSLayoutConstraint, UIButton, UILabel;
@protocol TransitGuidanceSignAccessoryViewProtocol;

__attribute__((visibility("hidden")))
@interface TransitGuidanceSignAccessoryView : UIView
{
    NSLayoutConstraint *_topToLabelConstraint;
    NSLayoutConstraint *_labelToButtonConstraint;
    NSLayoutConstraint *_topToButtonConstraint;
    NSLayoutConstraint *_labelToBottomConstraint;
    NSLayoutConstraint *_buttonToBottomConstraint;
    UIView *_dimmingView;
    _Bool _dimmed;
    id <TransitGuidanceSignAccessoryViewProtocol> _delegate;
    UIButton *_button;
    UILabel *_label;
    NSArray *_incidents;
}

+ (id)preferredIncidentTextAttributes;
+ (id)preferredMessageTextAttributes;
@property(nonatomic, getter=isDimmed) _Bool dimmed; // @synthesize dimmed=_dimmed;
@property(retain, nonatomic) NSArray *incidents; // @synthesize incidents=_incidents;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(nonatomic) __weak id <TransitGuidanceSignAccessoryViewProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setTransitRoutingIncidentAttributedText:(id)arg1;
- (void)setAccessoryAttributedText:(id)arg1;
- (void)setPreferredMaxLayoutWidth:(double)arg1;
- (id)_fontForButton:(id)arg1;
- (id)_fontForLabel:(id)arg1;
- (void)_incidentButtonTapped:(id)arg1;
- (void)_updateConstraintsValue;
- (void)_createConstraints;
- (void)_createSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

