//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface TransitAppRanker : NSObject <NSSecureCoding>
{
    NSMutableArray *_rankings;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSMutableArray *rankings; // @synthesize rankings=_rankings;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)recentlyLaunchedApps;
- (void)recordAppLaunch:(id)arg1;
- (id)rankApps:(id)arg1;
- (id)initWithRecentlyLaunchedApps:(id)arg1;
- (id)rankedTransitAppsProxiesWithProxies:(id)arg1;

@end

