//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MapsThemeView.h"

@class NSLayoutConstraint, NSMutableArray, NSString, UILabel;

__attribute__((visibility("hidden")))
@interface TrayHeaderLabelView : MapsThemeView
{
    NSMutableArray *_defaultLayoutConstraints;
    NSLayoutConstraint *_defaultLayoutInterLabelConstraint;
    NSMutableArray *_minimizedLayoutConstraints;
    NSString *_secondaryText;
    NSString *_minimizedSecondaryText;
    unsigned long long _layout;
    long long _layoutSize;
    UILabel *_primaryLabel;
    UILabel *_secondaryLabel;
}

@property(retain, nonatomic) UILabel *secondaryLabel; // @synthesize secondaryLabel=_secondaryLabel;
@property(retain, nonatomic) UILabel *primaryLabel; // @synthesize primaryLabel=_primaryLabel;
@property(nonatomic) long long layoutSize; // @synthesize layoutSize=_layoutSize;
@property(nonatomic) unsigned long long layout; // @synthesize layout=_layout;
- (void).cxx_destruct;
- (void)updateTheme;
- (void)setPrimaryText:(id)arg1 secondaryText:(id)arg2 minimizedSecondaryText:(id)arg3;
- (void)setPrimaryText:(id)arg1 secondaryText:(id)arg2;
- (void)_updateFontsWithLayoutSize:(long long)arg1;
- (void)_updateViewsWithLayout:(unsigned long long)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)setupConstraints;
- (void)setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

