//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIVisualEffectView.h>

@class UILabel;

__attribute__((visibility("hidden")))
@interface VisualEffectWrappingView : UIVisualEffectView
{
    UILabel *_label;
}

- (void).cxx_destruct;
- (id)viewForLastBaselineLayout;
- (id)viewForFirstBaselineLayout;
@property(retain, nonatomic) UILabel *label;

@end

