//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosEditUI/__PUAdjustmentsModeBarAccessibility_super.h>

@interface PUAdjustmentsModeBarAccessibility : __PUAdjustmentsModeBarAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)configureSliderCell:(id)arg1 forMode:(id)arg2;
- (void)_axLoadSliderCell:(id)arg1;
- (void)configurePickerCell:(id)arg1 forMode:(id)arg2;
- (void)_axSetAdjustmentsToolController:(id)arg1;
- (void)_setAXAdjustmentsToolController:(id)arg1;
- (id)_axAdjustmentsToolController;
- (void)_accessibilityLoadAccessibilityInformation;

@end

