/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:12 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class RTDeviceMO, NSString, NSData, NSUUID, NSDate;

@interface RTCloudManagedObject : NSManagedObject

@property (nonatomic,retain) RTDeviceMO * device; 
@property (nonatomic,copy) NSString * ckRecordID; 
@property (nonatomic,copy) NSData * ckRecordSystemFields; 
@property (nonatomic,copy) NSUUID * identifier; 
@property (nonatomic,copy) NSDate * creationDate; 
@property (nonatomic,copy) NSDate * expirationDate; 
-(void)awakeFromInsert;
-(NSUUID *)identifier;
-(void)setIdentifier:(NSUUID *)arg1 ;
@end

