/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:10 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/RTCoreDataTransformable.h>

@class GEORoute, NSUUID, NSDate, NSString;

@interface RTGeoRoute : NSObject <RTCoreDataTransformable> {

	GEORoute* _geoRoute;
	NSUUID* _identifier;
	NSUUID* _originLocationOfInterestIdentifier;
	NSUUID* _destinationLocationOfInterestIdentifier;
	NSDate* _creationDate;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) GEORoute * geoRoute;                                           //@synthesize geoRoute=_geoRoute - In the implementation block
@property (nonatomic,readonly) NSUUID * identifier;                                           //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,readonly) NSUUID * originLocationOfInterestIdentifier;                   //@synthesize originLocationOfInterestIdentifier=_originLocationOfInterestIdentifier - In the implementation block
@property (nonatomic,readonly) NSUUID * destinationLocationOfInterestIdentifier;              //@synthesize destinationLocationOfInterestIdentifier=_destinationLocationOfInterestIdentifier - In the implementation block
@property (nonatomic,readonly) NSDate * creationDate;                                         //@synthesize creationDate=_creationDate - In the implementation block
-(GEORoute *)geoRoute;
-(NSDate *)creationDate;
-(NSUUID *)originLocationOfInterestIdentifier;
-(NSUUID *)destinationLocationOfInterestIdentifier;
-(id)managedObjectWithContext:(id)arg1 ;
-(id)initWithGEORoute:(id)arg1 identifier:(id)arg2 originLocationOfInterestIdentifier:(id)arg3 destinationLocationOfInterestIdentifier:(id)arg4 creationDate:(id)arg5 ;
-(id)initWithGEORoute:(id)arg1 originLocationOfInterestIdentifier:(id)arg2 destinationLocationOfInterestIdentifier:(id)arg3 ;
-(id)initWithGeoRouteMO:(id)arg1 ;
-(NSUUID *)identifier;
@end

