/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:12 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTMapItemProviderBase.h>
#import <libobjc.A.dylib/RTMapItemProvider.h>

@class RTEventManager, RTMapServiceManager, NSString;

@interface RTMapItemProviderEventKit : RTMapItemProviderBase <RTMapItemProvider> {

	RTEventManager* _eventManager;
	RTMapServiceManager* _mapServiceManager;

}

@property (nonatomic,retain) RTEventManager * eventManager;                        //@synthesize eventManager=_eventManager - In the implementation block
@property (nonatomic,retain) RTMapServiceManager * mapServiceManager;              //@synthesize mapServiceManager=_mapServiceManager - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(RTMapServiceManager *)mapServiceManager;
-(void)setMapServiceManager:(RTMapServiceManager *)arg1 ;
-(id)mapItemsWithinDistance:(double)arg1 location:(id)arg2 startDate:(id)arg3 endDate:(id)arg4 error:(id*)arg5 ;
-(void)setEventManager:(RTEventManager *)arg1 ;
-(RTEventManager *)eventManager;
-(id)initWithDistanceCalculator:(id)arg1 eventManager:(id)arg2 mapServiceManager:(id)arg3 ;
-(id)init;
@end

