/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:12 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface RTParkingQualityProvider : NSObject {

	NSMutableArray* _movingHistorgram;
	unsigned long long _parkingQualityIndicator;

}

@property (nonatomic,retain) NSMutableArray * movingHistorgram;                       //@synthesize movingHistorgram=_movingHistorgram - In the implementation block
@property (assign,nonatomic) unsigned long long parkingQualityIndicator;              //@synthesize parkingQualityIndicator=_parkingQualityIndicator - In the implementation block
-(unsigned long long)calculateParkingQualityWithLocations:(id)arg1 parkingTimestamp:(double)arg2 ;
-(NSMutableArray *)movingHistorgram;
-(void)setParkingQualityIndicator:(unsigned long long)arg1 ;
-(unsigned long long)classifySamples:(id)arg1 ;
-(unsigned long long)parkingQualityToLocationQuality:(unsigned long long)arg1 ;
-(id)getHistogramFromSamples:(id)arg1 ;
-(id)getCdfFromHistogram:(id)arg1 numSamples:(double)arg2 ;
-(int)indexOfSmallestElement:(double*)arg1 size:(int)arg2 ;
-(unsigned long long)parkingQualityIndicator;
-(void)setMovingHistorgram:(NSMutableArray *)arg1 ;
-(id)init;
-(void)reset;
@end

