/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:10 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObjectContext.h>

@protocol RTPersistenceContextDelegate;
@interface RTPersistenceContext : NSManagedObjectContext {

	long long _mirroringQualityOfService;
	id<RTPersistenceContextDelegate> _delegate;

}

@property (__weak) id<RTPersistenceContextDelegate> delegate;                  //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) long long mirroringQualityOfService;              //@synthesize mirroringQualityOfService=_mirroringQualityOfService - In the implementation block
-(id)executeRequest:(id)arg1 error:(id*)arg2 ;
-(unsigned long long)countForFetchRequest:(id)arg1 error:(id*)arg2 ;
-(id)executeFetchRequest:(id)arg1 error:(id*)arg2 ;
-(BOOL)_processError:(inout id*)arg1 ;
-(long long)mirroringQualityOfService;
-(void)setMirroringQualityOfService:(long long)arg1 ;
-(void)setDelegate:(id<RTPersistenceContextDelegate>)arg1 ;
-(id<RTPersistenceContextDelegate>)delegate;
-(BOOL)save:(id*)arg1 ;
@end

