/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:12 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTPredictedLocationOfInterest, RTMapItem, NSString, RTLOIDisplayInfo;

@interface RTPLOIETA : NSObject {

	RTPredictedLocationOfInterest* _ploi;
	RTMapItem* _origin;
	unsigned _responseETASeconds;
	unsigned _baselineETASeconds;
	NSString* _responseRouteDescription;
	RTLOIDisplayInfo* _displayInfo;

}

@property (nonatomic,readonly) RTPredictedLocationOfInterest * ploi;              //@synthesize ploi=_ploi - In the implementation block
-(unsigned long long)trafficDensity;
-(id)mapsURL;
-(id)displayInfo;
-(id)localizedMessage;
-(RTPredictedLocationOfInterest *)ploi;
-(BOOL)hasEquivalentDisplayTo:(id)arg1 ;
-(BOOL)etaExceedsMinimumETA:(unsigned)arg1 ;
-(id)initWithPLOI:(id)arg1 origin:(id)arg2 responseETASeconds:(unsigned)arg3 baselineETASeconds:(unsigned)arg4 responseRouteDescription:(id)arg5 ;
-(id)_displayInfoForDate:(id)arg1 ;
-(id)description;
-(id)localizedTitle;
-(id)localizedDescription;
@end

