/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:11 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
@interface RTPriorityQueue : NSObject {

	CFBinaryHeapRef _heap;

}

@property (nonatomic,readonly) unsigned long long count; 
-(id)peek;
-(id)dequeue;
-(void)enqueue:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(unsigned long long)count;
-(id)initWithObjects:(id)arg1 ;
@end

