/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:10 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSNumber, RTPredictionTableEntryMO;

@interface RTPredictionItemMO : NSManagedObject

@property (nonatomic,retain) NSNumber * confidence; 
@property (nonatomic,retain) RTPredictionTableEntryMO * entry; 
@end

