/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:10 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTSystemControl : NSObject
+(id)valueForMib:(int*)arg1 miblen:(int)arg2 ;
+(unsigned long long)sysctlByName:(id)arg1 ;
+(id)valueForKey:(id)arg1 ;
@end

