//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SafariServices/_SFPopoverPresentationDelegate.h>

@interface _SFPopoverPresentationDelegate (SafariExtras)
+ (void)safari_attachDelegateToPopoverPresentationController:(id)arg1 browserController:(id)arg2 presentingFromBarItem:(long long)arg3;
@end

