//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface SafariClearBrowsingDataController : NSObject
{
    NSArray *_availableIntervals;
}

@property(readonly) NSArray *availableIntervals; // @synthesize availableIntervals=_availableIntervals;
- (void).cxx_destruct;
- (void)_clearBrowsingDataAddedAfterDate:(id)arg1;
- (void)clearAllBrowsingData;
- (void)clearDataFromInterval:(id)arg1;
- (id)init;

@end

