//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__MTEpisodeCollectionViewCellAccessibility_super.h"

@interface MTEpisodeCollectionViewCellAccessibility : __MTEpisodeCollectionViewCellAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_accessibilityUserTestingChildren;
- (unsigned long long)accessibilityTraits;
- (id)_privateAccessibilityCustomActions;
- (_Bool)_accessibilityDeleteAction;
- (id)_accessibilitySupplementaryFooterViews;
- (id)accessibilityLabel;
- (id)_axLockup;
- (void)setExpanded:(_Bool)arg1;
- (_Bool)isAccessibilityElement;

@end

