//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSMutableDictionary, NSString;

@interface PSDIDSServiceStatisticsCollection : NSObject <NSSecureCoding>
{
    NSMutableDictionary *_statistics;
    NSString *_channelName;
}

+ (id)knownChannelNames;
+ (id)statisticsCollectionWithChannelName:(id)arg1 statisticsDictionary:(id)arg2;
+ (_Bool)supportsSecureCoding;
@property(copy, nonatomic) NSString *channelName; // @synthesize channelName=_channelName;
- (void).cxx_destruct;
- (id)description;
- (id)statisticsCollectionByDiffingStatisticsCollection:(id)arg1;
- (void)addServiceStatistics:(id)arg1;
- (id)statisticsForServiceName:(id)arg1;
- (void)enumerateServiceStatisticsWithBlock:(CDUnknownBlockType)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

