//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PSYActivityProgress-Protocol.h"

@class NSString, PSDActivity;

@interface PSDServiceProgressDelegate : NSObject <PSYActivityProgress>
{
    PSDActivity *_service;
}

@property(nonatomic) __weak PSDActivity *service; // @synthesize service=_service;
- (void).cxx_destruct;
- (oneway void)activityDidUpdateProgress:(float)arg1;
- (oneway void)activityDidCompleteSending;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

