//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpringBoardUIServices/SBUIRemoteAlertServiceViewController.h>

@interface TrustMeRotatingViewController : SBUIRemoteAlertServiceViewController
{
    unsigned long long _mask;
}

- (void)dismissSheetAndDismissAlert;
- (void)_willAppearInRemoteViewController;
- (void)handleHomeButtonPressed;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)prefersStatusBarHidden;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

@end

