/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:58:29 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/log/liblog_companionsync.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <liblog_companionsync.dylib/liblog_companionsync.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface SYLogPeerIDPair : PBCodable <NSCopying> {

	NSString* _generationID;
	NSString* _peerID;

}

@property (nonatomic,retain) NSString * peerID;                    //@synthesize peerID=_peerID - In the implementation block
@property (nonatomic,readonly) BOOL hasGenerationID; 
@property (nonatomic,retain) NSString * generationID;              //@synthesize generationID=_generationID - In the implementation block
-(void)setPeerID:(NSString *)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(NSString *)peerID;
-(BOOL)hasGenerationID;
-(NSString *)generationID;
-(void)setGenerationID:(NSString *)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)copyTo:(id)arg1 ;
@end

