//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@class LUIManagedDevicesViewController;

@interface LUIManagedDevicesNavigationController : UINavigationController
{
    LUIManagedDevicesViewController *_managedDevicesViewController;
}

@property(retain, nonatomic) LUIManagedDevicesViewController *managedDevicesViewController; // @synthesize managedDevicesViewController=_managedDevicesViewController;
- (void).cxx_destruct;
- (void)doneButtonPressed:(id)arg1;
- (void)_setupNavigationItem;
- (id)initWithOrganizationName:(id)arg1;

@end

