//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CNContact, CNMonogrammer, NSOperationQueue, UIImageView;

@interface LUIUserAvatarView : UIView
{
    CNMonogrammer *monogrammer;
    UIImageView *imageView;
    NSOperationQueue *mOperationQueue;
    CNContact *_contact;
    double _monogramDiameter;
    long long _style;
    double _imageViewAlpha;
}

@property(nonatomic) double imageViewAlpha; // @synthesize imageViewAlpha=_imageViewAlpha;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(nonatomic) double monogramDiameter; // @synthesize monogramDiameter=_monogramDiameter;
@property(retain, nonatomic) CNContact *contact; // @synthesize contact=_contact;
- (void).cxx_destruct;
- (void)updateMonogram;
- (_Bool)_isDistortedImage:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

