//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUICore/___PXUIScrollViewAccessibility_super.h>

@interface _PXUIScrollViewAccessibility : ___PXUIScrollViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (_Bool)_accessibilityScrollAcrossPageBoundaries;
- (_Bool)_accessibilityOnlyComparesByXAxis;
- (long long)_axCompareView:(id)arg1 toView:(id)arg2;
- (id)_accessibilitySortedElementsWithin;
- (_Bool)isAccessibilityOpaqueElementProvider;

@end

