//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUIFramework/__PULivePhotoTrimScrubberAccessibility_super.h>

@interface PULivePhotoTrimScrubberAccessibility : __PULivePhotoTrimScrubberAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)setTrimEndTime:(CDStruct_1b6d18a9)arg1;
- (void)setTrimStartTime:(CDStruct_1b6d18a9)arg1;
- (void)_PULivePhotoTrimScrubber_commonInit;
- (id)accessibilityElements;
- (void)_accessibilityLoadAccessibilityInformation;
- (id)_accessibilitySummaryElement;
- (void)_setAXSummaryElement:(id)arg1;
- (id)_axSummaryElement;
- (void)_loadKeyFrameAX;
- (void)_loadEndTrimAX;
- (void)_loadStartTrimAX;
- (id)_accessibilityTimeForCMTime:(CDStruct_1b6d18a9)arg1;

@end

