//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class UIImage;

@interface WDPlayButtonLayer : CALayer
{
    CALayer *_playSymbolLayer;
}

@property(retain, nonatomic) CALayer *playSymbolLayer; // @synthesize playSymbolLayer=_playSymbolLayer;
- (void).cxx_destruct;
- (void)layoutSublayers;
@property(readonly, nonatomic) UIImage *playImage;

@end

