//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__RemindersUITextViewAccessibility_super.h"

@class RemindersCheckboxCellAccessibility;

@interface RemindersUITextViewAccessibility : __RemindersUITextViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityHint;
- (_Bool)isAccessibilityElement;
- (_Bool)_axIsNonEditingCreationFooterView;
- (_Bool)_axIsCheckboxCellTextView;
@property(nonatomic) _Bool accessibilityIsRemindersCreationFooterViewTextView;
@property(nonatomic) __weak RemindersCheckboxCellAccessibility *accessibilityCheckboxCell;

@end

