//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SYDScheduler;

@interface SYDBackgroundScheduler : NSObject
{
    SYDScheduler *_scheduler;
    NSString *_identifier;
    _Bool _allowsCellular;
}

+ (void)removeBackgroundScheduler:(id)arg1;
+ (void)addBackgroundScheduler:(id)arg1;
+ (void)initialize;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) SYDScheduler *scheduler; // @synthesize scheduler=_scheduler;
@property(nonatomic) _Bool allowsCellular; // @synthesize allowsCellular=_allowsCellular;
- (void).cxx_destruct;
- (void)_noteBackgroundSchedulerWasPinged;
- (void)shutdown;
- (_Bool)scheduleRelaunchWithDate:(double)arg1;
- (void)dealloc;
- (id)initWithScheduler:(id)arg1;

@end

