//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COSFeatureHighlightDataSource.h"

@interface COSCliftonFeatureDataSource : COSFeatureHighlightDataSource
{
    _Bool _hasHighBPMDetection;
    _Bool _hasLowBPMDetection;
}

@property(nonatomic) _Bool hasLowBPMDetection; // @synthesize hasLowBPMDetection=_hasLowBPMDetection;
@property(nonatomic) _Bool hasHighBPMDetection; // @synthesize hasHighBPMDetection=_hasHighBPMDetection;
- (id)features;

@end

