//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COSOptinViewController.h"

#import "PBAutomationDocumentation-Protocol.h"

@interface COSFitnessRouteOptinViewController : COSOptinViewController <PBAutomationDocumentation>
{
}

+ (_Bool)controllerNeedsToRun;
+ (id)radarComponent;
+ (id)documentationDescription;
+ (id)subViews;
+ (id)viewsAndActions;
- (void)selectedAboutDetail:(id)arg1;
- (id)detailTitleString;
- (id)learnMoreButtonTitle;
- (id)alternateButtonTitle;
- (id)suggestedButtonTitle;
- (void)alternateButtonPressed:(id)arg1;
- (void)suggestedButtonPressed:(id)arg1;
- (void)selectedOptinChoice:(_Bool)arg1;
- (id)imageResource;
- (id)detailString;
- (id)titleString;
- (_Bool)wantsLightenBlendedScreen;
- (id)init;

@end

