//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COSOptinViewController.h"

#import "COSBuddyController-Protocol.h"
#import "PBAutomationDocumentation-Protocol.h"

@class NSString;

@interface COSHealthChoiceViewController : COSOptinViewController <PBAutomationDocumentation, COSBuddyController>
{
}

+ (_Bool)controllerNeedsToRun;
+ (id)radarComponent;
+ (id)documentationDescription;
+ (id)subViews;
+ (id)viewsAndActions;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)learnMoreButtonPressed:(id)arg1;
- (void)suggestedButtonPressed:(id)arg1;
- (void)selectedMoreOptions:(id)arg1;
- (id)moreOptionsButtonString;
- (id)detailString;
- (id)detailTitleString;
- (id)learnMoreButtonTitle;
- (id)alternateButtonString;
- (id)suggestedButtonTitle;
- (id)imageResource;
- (id)titleString;
- (_Bool)wantsLightenBlendedScreen;
- (_Bool)legacyButtonStyles;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

