//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface COSOptinFYIController : NSObject
{
}

+ (id)unifiedFYIDescription;
+ (void)doWorkForSkippedPanes;
+ (_Bool)wantsUnifiedFYIPane;
+ (_Bool)_wantsUnifiedFYIPane;
+ (void)clearState;
+ (void)snapshotState;

@end

