//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Preferences/PSListController.h>

#import "PBAutomationDocumentation-Protocol.h"

@interface COSPairedDeviceListViewController : PSListController <PBAutomationDocumentation>
{
}

+ (id)radarComponent;
+ (id)documentationDescription;
+ (id)subViews;
+ (id)viewsAndActions;
- (void)pushActiveDeviceDetails;
- (void)deviceBecameInactive:(id)arg1;
- (void)deviceBecameActive:(id)arg1;
- (void)_showBackButtonBehavior:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)pushCellDetailForRowWithIndexPath:(id)arg1 animate:(_Bool)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)switchToDevice:(id)arg1;
- (void)selectDeviceWithSpecifier:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)dealloc;
- (id)init;

@end

