//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Preferences/PSSoftwareUpdateAnimatedIcon.h>

@class NSString, UIImageView;

@interface COSSoftwareUpdateAnimatedIcon : PSSoftwareUpdateAnimatedIcon
{
    NSString *_outerGearImageName;
    UIImageView *_outerGear;
}

@property(retain, nonatomic) UIImageView *outerGear; // @synthesize outerGear=_outerGear;
@property(retain, nonatomic) NSString *outerGearImageName; // @synthesize outerGearImageName=_outerGearImageName;
- (void).cxx_destruct;
- (id)outerGearView;
- (id)outerGearShadowView;
- (id)innerGearView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

