//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "COSAppInstallationDelegate-Protocol.h"
#import "COSBuddyController-Protocol.h"
#import "PBAutomationDocumentation-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"

@class COSAppInstallationController, NSString, UIButton, UIImageView, UILabel;
@protocol COSBuddyControllerDelegate;

@interface COSVictoryChoiceViewController : UIViewController <SKStoreProductViewControllerDelegate, COSAppInstallationDelegate, PBAutomationDocumentation, COSBuddyController>
{
    id <COSBuddyControllerDelegate> _delegate;
    UIImageView *_victoryLogoFloating;
    UILabel *_titleLabel;
    UILabel *_descriptionLabel;
    UIImageView *_backgroundView;
    UIButton *_acceptButton;
    UIButton *_skipButton;
    COSAppInstallationController *_installController;
}

+ (_Bool)controllerNeedsToRun;
+ (id)radarComponent;
+ (id)documentationDescription;
+ (id)subViews;
+ (id)viewsAndActions;
@property(retain, nonatomic) COSAppInstallationController *installController; // @synthesize installController=_installController;
@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(retain, nonatomic) UIButton *acceptButton; // @synthesize acceptButton=_acceptButton;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *victoryLogoFloating; // @synthesize victoryLogoFloating=_victoryLogoFloating;
@property(nonatomic) __weak id <COSBuddyControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)appIsAvailableStateDidChange:(unsigned long long)arg1;
- (void)didCompleteInstallationWithSuccess:(_Bool)arg1;
- (void)didBeginInstallationWithSuccess:(_Bool)arg1;
- (void)didInitiatePurchase;
- (void)setButtonEnabled:(_Bool)arg1;
- (void)selectedSkipUpdate:(id)arg1;
- (void)selectedUpdate:(id)arg1;
- (void)selectedContinue:(id)arg1;
- (void)selectedInstallLater:(id)arg1;
- (void)selectedInstall:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)updateControllerState;
- (void)viewDidLoad;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

