//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, WristDetect_3_0;

@interface COSWristAttributeVisualDetector : NSObject
{
    NSMutableArray *_confidenceObservations;
    WristDetect_3_0 *_model;
}

@property(retain, nonatomic) WristDetect_3_0 *model; // @synthesize model=_model;
@property(retain, nonatomic) NSMutableArray *confidenceObservations; // @synthesize confidenceObservations=_confidenceObservations;
- (void).cxx_destruct;
- (void)exportSample:(struct opaqueCMSampleBuffer *)arg1 withClassification:(unsigned long long)arg2;
- (void)ingestSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (struct __CVBuffer *)pixelBufferFromCGImage:(struct CGImage *)arg1;
- (struct CGImage *)resizedImageFromImage:(struct CGImage *)arg1;
- (struct CGImage *)createImageFromSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (id)computedConfidences;
- (id)confidenceSummary;
- (id)init;

@end

