//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface S3AccessConfig : NSObject
{
    NSString *_AWSAccessKeyID;
    NSString *_AWSSecretAccessKey;
}

@property(retain, nonatomic) NSString *AWSSecretAccessKey; // @synthesize AWSSecretAccessKey=_AWSSecretAccessKey;
@property(retain, nonatomic) NSString *AWSAccessKeyID; // @synthesize AWSAccessKeyID=_AWSAccessKeyID;
- (void).cxx_destruct;
- (id)initWithAWSAccessKeyID:(id)arg1 AWSSecretAccessKey:(id)arg2;

@end

