/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:20:25 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/system/libsystem_trace.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct {
	unsigned field1 : 4;
	unsigned field2 : 4;
	unsigned char field3;
	unsigned char field4[0];
} SCD_Struct_OS0;

