/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 2, 2019 at 4:20:25 AM Central European Standard Time
* Operating System: Version 12.1.2 (Build 16C104)
* Image Source: /usr/lib/system/libsystem_trace.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_object.h>

@interface OS_os_log : OS_object
+(void)load;
-(void)_dispose;
@end

